창작자 인증 뮤테이션 구현
penxle/penxle pull request #1046
Opened 2024-01-09 08:55 UTC by robin-maki

2024-01-09 08:55 UTC, robin-maki commented
Current dependencies on/for this PR:
* `main`
  * **PR #1046** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1046?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/1046?utm_source=stack-comment).

2024-01-10 02:47 UTC, devunt requested changes

2024-01-10 02:47 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +        }
P3: 그럼 주민번호 앞자리는 따로 받을 필요 없지 않을까여? 프론트에서 애초에 뒷자리만 받아와도 될 것 같기도 (UI에는 `personalIdentity.birthday` 기반으로 채워서 보여주고)

2024-01-10 02:47 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +        const { encrypted, nonce } = await encryptAES(`${input.residentNumberFront}-${input.residentNumberBack}`);
P1: 저장할 때 중간에 `-` 는 빼 주세용

2024-01-10 02:47 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +        });
P2: 계좌번호는 바꿀 수 있어야 하는게 맞는데 주민번호는 바뀔 수 있으면 안 될 거 같아여 (만약 바꾼다면 cs를 태워야 할 듯)

2024-01-10 02:47 UTC, devunt commented on apps/penxle.com/src/lib/server/utils/aes.ts
> +    encrypted: btoa(String.fromCodePoint(...new Uint8Array(encrypted))),
P2: `Buffer.from(...).toString('base64')` 로는 안 되나용

2024-01-10 02:47 UTC, devunt commented on apps/penxle.com/src/lib/server/utils/aes.ts
> +    Uint8Array.from(atob(encrypted), (c) => c.charCodeAt(0)),
P2: `Buffer.from(..., 'base64')` 로는 안 되나용

2024-01-10 09:02 UTC, devunt requested changes

2024-01-10 09:02 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +        const residentRegistrationNumber = `${dayjs(personalIdentity.birthday).tz('Asia/Seoul').format('YYMMDD')}${
P1: `.tz(...)` 말고 `.kst()` 해도 될걸요?!

2024-01-10 09:02 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  encryptedResidentRegistrationNumberNonce String @map("encrypted_resident_registration_number_nonce")
P1: 주민번호 해시도 추가해주세요!

2024-01-10 09:02 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +model UserCreatorIdentity {
P3: 이름 고민해보기...

2024-01-11 02:43 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +model UserCreatorIdentity {
갑자기 생각난 단어인데 `UserWithdrawalInfo`는 어떤가요??

2024-01-11 05:01 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +model UserCreatorIdentity {
`UserSettlementIdentity`로 결정

2024-01-11 05:09 UTC, devunt requested changes

2024-01-11 05:09 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +    verifyCreatorIdentity: t.withAuth({ user: true }).prismaField({
P1: `verifySettlementIdentity` ?

2024-01-11 05:09 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +        const creatorIdentity = await db.userSettlementIdentity.findUnique({
P1: `settlementIdentity` ?

2024-01-11 05:29 UTC, robin-maki commented
@Seohyun-Roh `creatorIdentity` 라는 이름이 전부 `settlementIdentity`로 바뀌었어요!

2024-01-11 05:34 UTC, devunt approved these changes

2024-01-11 05:56 UTC, robin-maki commented
저는바보입니다... #935 에서 마이그레이션을 생성해버린 바람에 저걸 먼저 머지하지 않으면 마이그레이션을 만들기가 어렵네요...

2024-01-15 02:48 UTC, merged