수익금 출금 동작 구현
penxle/penxle pull request #1069
Opened 2024-01-12 09:23 UTC by robin-maki

2024-01-12 09:23 UTC, robin-maki commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/penxle/penxle/1069?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1046** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1046?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1069** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1069?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #1052** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1052?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/1069?utm_source=stack-comment).

2024-03-08 05:54 UTC, devunt requested changes
P1: 아마 got이 에러나면 throw할텐데 지금 로직은 전반적으로 슬랙 웹훅을 실패하면 출금 자체가 실패하게 짜여져 있는 거 같아용 슬랙 장애났을 때도 출금 되게 하려면 슬랙 관련 로직 전부 감싸는게 좋을 듯? 지금 슬랙쪽 코드 계속 반복되고 있는데 밑에 따로 함수로 빼도 좋을 거 같구

2024-03-08 05:54 UTC, devunt commented on apps/penxle.com/src/lib/server/utils/revenue.ts
> +  const dateCondition = dayjs().kst().subtract(7, 'day').toDate();
P3: kst로 계산하는 이유가 모에여??

2024-03-08 05:54 UTC, devunt commented on apps/penxle.com/src/lib/server/utils/revenue.ts
> +    throw new IntentionalError('먼저 창작자 인증을 진행해 주세요');
P3: 창작자 인증 워딩 고민 필요 (회의에서 합시다)

2024-03-08 05:54 UTC, devunt commented on apps/penxle.com/src/lib/server/utils/revenue.ts
> +    txId = await transferOut({
P2: `coocon` 임포트해서 `coocon.transferOut()` 해주세용

2024-03-08 05:54 UTC, devunt commented on apps/penxle.com/src/lib/server/utils/revenue.ts
> +    });
P1: `transferOut` 한 뒤에 `verifyTransferOut` 까지 진행해주세용

2024-03-08 05:59 UTC, devunt requested changes

2024-03-08 05:59 UTC, devunt commented on apps/penxle.com/src/lib/server/utils/revenue.ts
> +  await db.$commit();
P1: 커밋하면 위에서 걸었던 락 풀려요. 중간에 커밋할거면 커밋하고 트랜잭션 다시 열고 락 다시 걸어야 할 듯?

2024-03-08 05:59 UTC, devunt commented on apps/penxle.com/src/lib/server/utils/revenue.ts
> +      memo: `수익출금_${settlement.id}`,
`settlement.id`가 아마 20글자가 넘을텐데 은행 메모는 최대 8글자 정도라 다 안 들어가요. 메모는 에러났거나 나중에 결산할 때 대조용으로 기록하는거라 8글자정도의 대조용 ID 따로 파거나 다른 방법이 필요할 듯? nanoid가 은행 메모에 들어가기에 세이프한 글자들일거라 8글자짜리 nanoid 생성하는 것도 괜찮을 듯. 지금은 실제로 cuid2의 앞 3~4자 정도만 기록될거에요

2024-03-08 06:04 UTC, robin-maki commented on apps/penxle.com/src/lib/server/utils/revenue.ts
> +  const dateCondition = dayjs().kst().subtract(7, 'day').toDate();
앗 첨엔 자정 기준이였어서 들어갔을 거 같아요...

2024-03-14 03:20 UTC, devunt approved these changes

2024-03-14 03:28 UTC, merged