여권인증 프론트 구현
penxle/penxle pull request #1116
Opened 2024-01-23 10:20 UTC by Seohyun-Roh

2024-01-23 10:21 UTC, Seohyun-Roh commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/penxle/penxle/1116?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1114** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1114?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1116** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1116?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/1116?utm_source=stack-comment).

2024-01-24 05:07 UTC, devunt requested changes

2024-01-24 05:07 UTC, devunt commented on apps/penxle.com/src/routes/(default)/me/settings/VerifyPassportIdentityModal.svelte
> +      </FormField>
P2: 이거 한글 이름이라고 명시하는게 좋을 거 같아요. 여권이라서 여권상 표기된 영문 이름 적는 사람 많을 거 같은데 실제로는 한글로 된 한국 이름 입력해야 해요

2024-01-24 05:30 UTC, x86chi commented on apps/penxle.com/src/routes/(default)/me/settings/VerifyPassportIdentityModal.svelte
> +        <TextInput minlength={8} placeholder="생년월일 8자리" />
P2: 접근성 관련해서 두가지 의견

## input type="numeric"

모바일 등 가상 키보드를 사용하는 환경에서 입력을 쿼티 자판 대신에 숫자 키패드로 보여주기 위해 type="numeric" 를 지정하는 걸 권장드립니다.

##  placeholder

> placeholder text is not a replacement for labels. 
> https://www.w3.org/WAI/tutorials/forms/instructions/#placeholder-text

 WAI 지침에 따르면 플레이스홀더 텍스트는 입력 값의 예시를 넣어줘야 된다고 나와 있는데, 카카오페이와 같이 예시 숫자 입력 값을 플레이스홀더에 넣어주는 게 어떨까 싶네요.

(카카오페이 예시)
 ![image](https://github.com/penxle/penxle/assets/5278201/47ccbeae-e404-440a-b4eb-863e7c0d2c48)


## 정리

```suggestion
        <TextInput minlength={8}  placeholder="예) 19840301" type="numeric" />
```

2024-01-24 06:18 UTC, devunt requested changes

2024-01-24 06:18 UTC, devunt commented on apps/penxle.com/src/routes/(default)/me/settings/VerifyPassportIdentityModal.svelte
> +      </FormField>
P2: 이거 예시 좀 더 우리 유저 평균 나이대랑 현실 예시에 맞추는게 어떨지?!?! 생년월일 `20030301` 여권 발행일자 `20210801` 여권 만료일자 `20310801` 뭐 이런 느낌으로??

2024-01-24 06:22 UTC, devunt approved these changes
👍

2024-01-24 06:27 UTC, merged