에디터 리뉴얼 데이터베이스 설계
penxle/penxle pull request #1123
Opened 2024-01-25 05:09 UTC by robin-maki

2024-01-25 05:10 UTC, robin-maki commented
Current dependencies on/for this PR:
* `main`
  * **PR #1123** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1123?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/1123?utm_source=stack-comment).

2024-01-25 06:29 UTC, devunt requested changes

2024-01-25 06:29 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  ADDITIONAL
P3: `EXTRA`? 지금 이름도 괜찮긴 한 듯

2024-01-25 06:29 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  WORK
P2: `TITLE`....? `PRODUCT`...?

2024-01-25 06:29 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +
P1: `PAIR` 있어야 하나요? 페어는 태그로 핸들링 안 하고 그냥 enum으로 하는게 나으려나 싶기도 하고 (여튼 뭐로 하든 지금은 구현이 안 되어 있는 듯)

2024-01-26 03:21 UTC, devunt requested changes

2024-01-26 03:21 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  pairs                  PostPair[]              @default([OTHER])
P2: 요거 기본적으로는 아예 비어있어야 하지 않을까여?

2024-01-26 03:21 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  autoIndent       Boolean @default(true) @map("auto_indent")
P1: 우리 문단 들여쓰기도 이제 수치 지정으로 바뀌어서 반영해야 할 듯 ?! `paragraphIndent` 같은거 하나 만들고 (일단 기본값은 `100`) `autoIndent`가 `false`면 `paragraphIndent`를 `0`으로 업뎃하는 쿼리 하나 날리면 될 거 같아여

2024-01-26 03:21 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  OTHER
P3: 요거 프론트 용어랑 맞추는게 좋지 않을까여??
```
BL
GL
HL
NONCP (NCP?)
OTHER
```

(여러개 선택 가능하니까 `MULTIPLE`은 없어도 될 것 같기도...?!)

2024-01-26 03:21 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  PRODUCT
P4: 프로덕트가 맞나............... 고민됨 (너무 상품같아서)

2024-01-26 03:26 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +  pairs                  PostPair[]              @default([OTHER])
페어는 빈 배열로 만들면 되긴 하는데... 나머지 값은 일단 있어야 마이그레이션에서 안 박살나지 않을까요...???

2024-01-26 03:27 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  pairs                  PostPair[]              @default([OTHER])
오 네 페어 말한거였어여 !!

2024-01-26 03:29 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +  OTHER
프론트 용어를 그렇게 쓰나요?? 뭔가 BL GL이 지금 동인계에서 좀 더 협소한 의미로 쓰이고 있어서 조금 걱정이 되네요...
그리고 MULTIPLE은 커플이 3명 이상일 케이스도 있어서...

2024-01-26 04:43 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  OTHER
요거 #product 에서 얘기해보는게 좋을 듯

2024-01-26 06:13 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +  PRODUCT
`WORK`보다 더 좋은 이름이 생각이 안 나요...

2024-01-26 10:24 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +  PRODUCT
`TITLE`로 하기로

2024-01-31 12:30 UTC, devunt approved these changes

2024-01-31 12:39 UTC, merged