컬러 피커 컴포넌트 추가하기
penxle/penxle pull request #1141
Opened 2024-01-30 05:23 UTC by x86chi

- [x] 기능 PoC 
- [ ] 스타일링

2024-01-30 05:23 UTC, x86chi commented
Current dependencies on/for this PR:
* `main`
  * **PR #1141** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1141?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/1141?utm_source=stack-comment).

2024-01-30 11:47 UTC, x86chi commented on apps/penxle.com/src/lib/components/ColorPicker.svelte
> +        on:keyup={updateHistory}
키보드 방향키로 박스 그라데이션 피커 UI 를 사용할 수 있게 지원했습니다.

2024-01-30 11:47 UTC, x86chi commented on apps/penxle.com/src/lib/components/ColorPicker.svelte
> +  }
컬러 입력 박스에 있는 기본 테두리를 제거하기 위해 추가했습니다.

2024-01-30 17:14 UTC, Seohyun-Roh requested changes

2024-01-30 17:14 UTC, Seohyun-Roh commented on apps/penxle.com/src/lib/components/ColorPicker.svelte
> +    gradientH.addColorStop(1, rgb.toString());
P2: color picker에서 직접 선택할 때는 괜찮은데 hex code를 input에 직접 입력할 경우 gradient가 이상하게 칠해지는 오류가 있습니다.

<img width="183" alt="image" src="https://github.com/penxle/penxle/assets/76952602/a84c64e5-3ecf-4a9e-870d-bde80683b8c2">

2024-01-31 05:12 UTC, x86chi commented on apps/penxle.com/src/lib/components/ColorPicker.svelte
> +    gradientH.addColorStop(1, rgb.toString());
구두로 이야기했듯이 그라데이션 슬라이더로 색상 변경 시 박스 그라데이션 피커 위치를 유지하도록 하는 건 시간 상 보류하고 추후 구현하겠습니다.

2024-01-31 05:16 UTC, Seohyun-Roh approved these changes

2024-01-31 05:24 UTC, merged