일부 스타일 새 디자인 시스템 맞춰서 업데이트
penxle/penxle pull request #1142
Opened 2024-01-30 07:51 UTC by devunt

- `shadow-box/50` 추가
- `.ProseMirror-dropcursor` 컬러 `teal-500` 으로 수정

2024-01-30 07:51 UTC, devunt commented
Current dependencies on/for this PR:
* `main`
  * **PR #1142** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1142?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #1143** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1143?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #1124** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1124?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/1142?utm_source=stack-comment).

2024-01-30 17:26 UTC, Seohyun-Roh requested changes

2024-01-30 17:26 UTC, Seohyun-Roh commented on packages/lib/src/unocss/preset.ts
> +      'box/50': '0 2px 10px 0 rgba(0, 0, 0, 0.04)',
P3: 요게 결제선에 쓰이는 shadow인가요? 그렇다면 box라는 이름은 조금 헷갈릴수도 있을 것 같아요..

2024-01-31 02:47 UTC, devunt commented on packages/lib/src/unocss/preset.ts
> +      'box/50': '0 2px 10px 0 rgba(0, 0, 0, 0.04)',
앗 요거 피그마에서 원래 이름이 `box/50` 이였는데 방금 확인해보니 `accessbarrier/50` 으로 바뀌었네요...! 여기 한 곳에만 쓰이는거라 그냥 프리셋에 추가 안 하고 인라인 클래스로 바꿨어용

2024-01-31 03:17 UTC, Seohyun-Roh approved these changes

2024-01-31 03:18 UTC, x86chi approved these changes

2024-01-31 03:55 UTC, merged