스페이스 DB 스키마
penxle/penxle pull request #126
Opened 2023-09-26 11:48 UTC by robin-maki

2023-09-26 11:48 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #126** <a href="https://app.graphite.dev/github/pr/penxle/penxle/126" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/126?utm_source=stack-comment).

2023-09-28 03:46 UTC, devunt requested changes

2023-09-28 03:46 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  avatar      Image?          @relation(fields: [avatarId], references: [id])
P3: 저희 이름 스페이스 아바타로 가나용 ??

2023-09-28 03:46 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  blockUsers SpaceBlockUser[]
P3: `blockedUsers` ?

2023-09-28 03:46 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +model SpaceBlockUser {
P3: `SpaceUserBlock` ? 테이블명은 다 명사로 짓는데 `SpaceBlockUser` 는 그냥 동사형 문장인 느낌....?

2023-09-28 03:46 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +model SpaceLink {
P5: `SpaceLink` 이름이 적당한지 잘 모르겠군요 음 link를 sso쪽에서 연결이라는 의미로 쓰고 있어서 그런가... 그렇다고 딱히 더 나은 이름이 생각나지도 않는 점

2023-09-28 03:46 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  category  SpaceLinkCategory
P3: 요거 따로 db나 백엔드에서는 `category` 넣지 말고 그냥 url 뭐로 시작하는지에 따라 프론트에서 다른 아이콘 보여주게 처리하는거 어떨까용 (각 주소에 대한 아이콘 매핑은 프론트에서 관리하고)

2023-09-28 03:46 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +model SpaceMemberInvite {
P3: 요거도 `SpaceMemberInvitation` ? 전체적으로 `invite` 를 다 `invitation` 으로 고치는게 어떨지요

2023-09-28 03:46 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  sentUserId     String                 @map("invite_user_id")
P1: 프리즈마 컬럼명이랑 매핑된 컬럼명이 완전 달라욧

2023-09-28 03:46 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  receivedUserId String                 @map("invited_user_id")
P1: 여기도 프리즈마 컬럼명이랑 매핑된 컬럼명이 완전 달라욧

2023-09-28 03:46 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  acceptedAt     DateTime?              @map("accepted_at") @db.Timestamptz
P2: 거절된 시간도 기록하려면 `acceptAt` 보다는 `reactedAt` ? 뭐 이런 좀 더 제네럴한 (둘 다 담을 수 있는) 이름이 좋을지도요... (큰 생각 없이 말한거라 `reactedAt`이 괜찮은지는 모르겠음)

2023-09-28 03:46 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +model SpaceTag {
P3: 스페이스 태그 목록은 유저가 적는게 아니라 실시간으로 갱신되는건데 DB에 넣어도 되나? 하는 생각 (redis에 넣어야 하지 않나? 고민되는군요)

2023-09-28 03:46 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  blockedSpaces            SpaceBlockUser[]
P1: 유저가 스페이스를 블록한게 아니라 스페이스가 유저를 블록한거니 `spacesBlockedBy` ...? 이 이름이 마음에 들진 않는데 일단 `blockedSpaces` 는 아닌 듯한 느낌

2023-09-28 03:46 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +model UserFollowingSpace {
P3: 요거도 `SpaceBlockUser`랑 마찬가지로 명사형 이름이면 좋겠어요! `UserSpaceFollowing` ?

2023-09-28 03:57 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +  avatar      Image?          @relation(fields: [avatarId], references: [id])
일단 프로필에서도 아바타라고 쓰고 있어서 이걸로 정했었어요

2023-09-28 03:59 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +model SpaceLink {
`SpaceExternalLink` 같은 느낌은 어떤가요??

2023-09-28 04:03 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +  acceptedAt     DateTime?              @map("accepted_at") @db.Timestamptz
`updatedAt`은... 지나치게 일반적일까요...?

2023-09-28 04:05 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +model SpaceTag {
사용자가 원하는 일부 태그를 고정시킬 수 있는 느낌?? 으로 생각해서 짠거라서 테이블에 저장되어 있는건 고정시킨 태그 + 포스트 현황에 따라 갱신되는건 Redis 이렇게 생각하고 설계했어요! (이 내용의 주석을 썼었는데 뭐가 꼬였는지 linter가 지워버렸네요...)

2023-09-28 04:47 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +model SpaceLink {
`SpaceExternalLink` 좋은거 같아요!

2023-09-28 04:48 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  acceptedAt     DateTime?              @map("accepted_at") @db.Timestamptz
좀 일반적이긴 하네요.... `respondedAt` ?

2023-09-28 04:49 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +model SpaceTag {
일부 태그 고정 기능 없을거에요 !! 아마 100% 실시간 갱신일거에용 @Seohyun-Roh

2023-09-28 05:26 UTC, Seohyun-Roh commented on apps/penxle.com/prisma/schema.prisma
> +model SpaceTag {
태그 고정을 넣을지말지 얘기가 나오긴했었는데 확실히 정해지지 않았어서.. 근데 일단 고정 태그에 대해 긍정적인 의견들이 있었던 것같긴합니당

2023-10-01 02:12 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  avatar      Image?          @relation(fields: [avatarId], references: [id])
저는 logo 아니면 icon 정도가 적당해보여요...!

2023-10-02 07:36 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +  avatar      Image?          @relation(fields: [avatarId], references: [id])
icon으로 수정했어요!

2023-10-02 10:03 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +model SpaceTag {
일단 첫 릴리즈에서는 빼고 나중에 피드백을 받아서 추가시키는 방향으로 해보죠!!

2023-10-04 03:08 UTC, devunt approved these changes
고생많으셨어요! 굿굿

2023-10-06 07:28 UTC, merged