모바일 에디터 동작 개선 및 디자인 추가 반영
penxle/penxle pull request #1279
Opened 2024-02-07 15:52 UTC by devunt

- 하단 에디터 툴바가 늘 키보드 위에 위치하도록 함
- 하단 에디터 툴바를 클릭해도 키보드가 사라지지 않도록 함
- 일부 요소 피그마와 디자인 맞춤
- 코드 정리함

2024-02-07 15:52 UTC, devunt commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/penxle/penxle/1279?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1265** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1265?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1271** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1271?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #1275** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1275?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #1279** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1279?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/1279?utm_source=stack-comment).

2024-02-07 17:01 UTC, Seohyun-Roh requested changes

2024-02-07 17:01 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/editor/[permalink]/Editor.svelte
> +  </div>
내용이 비어있을 때 에디터가 화면에 꽉 차지 않는 것 같은데 이부분 수정해야할 것 같아용 + 스크롤 없을 때는 스크롤 영역 안나타나게 overflow-auto로 하는게 어떨까요?
<img width="1439" alt="image" src="https://github.com/penxle/penxle/assets/76952602/96a08b36-d4e7-49c3-99bb-cd1121d67a89">

2024-02-07 17:09 UTC, Seohyun-Roh commented
`bottomMenu`때문에 키보드 이동이 생기는건 어쩔수 없기도 하고 이미 익숙한 플로우라고 생각해서 괜찮을것같아요.. 그렇다고 인용구랑 구분선을 subMenu에 넣기에는 애매하기도 하고.. 지금은 더 나은 방법이 생각나지 않네요 😭

2024-02-08 09:57 UTC, Seohyun-Roh approved these changes

2024-02-08 10:00 UTC, merged