스페이스 초대 기능 구현
penxle/penxle pull request #128
Opened 2023-09-27 08:25 UTC by robin-maki

2023-09-27 08:25 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #126** <a href="https://app.graphite.dev/github/pr/penxle/penxle/126" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #128** <a href="https://app.graphite.dev/github/pr/penxle/penxle/128" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/128?utm_source=stack-comment).

2023-10-01 02:16 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +    invites: t.prismaField({
P2: 요거 권한 없을 경우 빈 리스트 리턴하는거보단 authScope 이용하는게 더 나을 거 같아용

2023-10-01 02:28 UTC, devunt requested changes

2023-10-01 02:28 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +    invites: t.prismaField({
P2: 요거 권한 없을 경우 빈 리스트 리턴하는거보단 authScope 이용하는게 더 나을 거 같아용

2023-10-01 02:28 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +            sentUserId: ['OWNER', 'ADMIN'].includes(spaceMember.role) ? undefined : context.session.userId,
P3: 오너랑 어드민만 초대할 수 있는데 요거 체크가 의미가 있나요? 👀

2023-10-01 02:28 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +  select: { id: true },
P3: `authScopes.$granted` 통해서 접근 권한 제어 들어가면 좋을 거 같아요

2023-10-01 02:28 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +    nullable: true,
P2: 요거 왜 nullable인지?!

2023-10-01 02:28 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +            not: 'ACCEPTED',
P5: `state: 'PENDING'` 이 더 낫지 않을까 하는 생각도... idempotent한 동작을 생각한다면 지금이 맞는 거 같기도 하고...

2023-10-01 02:28 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +    type: 'SpaceMember',
P3: `acceptSpaceInvite` 랑 `ignoreSpaceInvite` 랑 리턴 타입이 같아야 할 거 같아요. 둘 다 `SpaceMemberInvitation`인게 논리적으로 보이기도.

2023-10-01 02:28 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +    receivedSpaceInvites: t.relation('receivedSpaceMemberInvites'),
P3: `receivedSpaceMemberInvitations` 가 나을 거 같아요. (좀 길긴 하지만... graphql relation 이름이랑 prisma relation 이름 맞추는게 베스트 프랙티스긴 한 듯)

2023-10-01 02:28 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +  inviteUserToSpace: t.withAuth({ user: true }).prismaField({
P4: 이름... `createSpaceMemberInvitation`이 나은 거 같기도... 아닌 거 같기도...

2023-10-01 02:28 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +  acceptSpaceInvite: t.withAuth({ user: true }).prismaField({
P4: 이름 `acceptSpaceMemberInvitation`이 나은 거 같기도....

2023-10-01 02:28 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +  ignoreSpaceInvite: t.withAuth({ user: true }).prismaField({
P4: 이름 `ignoreSpaceMemberInvitation` 이 나은 거 같기도...

2023-10-02 08:47 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +            sentUserId: ['OWNER', 'ADMIN'].includes(spaceMember.role) ? undefined : context.session.userId,
지금 생각해보니까 그렇긴 하네요... 초대 후 어드민 권한을 잃는 그런 케이스는 생각 안 해도 되겠죠...?

2023-10-02 08:59 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +  select: { id: true },
보낸 초대는 space의 authScopes로 해결할 수 있을 거 같은데 받은 초대는 좀 복잡해져서 오브젝트보단 쿼리에 스코프 체크를 하는 편이 더 나을 거 같아요 (제가 아직 인증 시스템에 대해 완벽히 이해하진 못해서 아닐수도 있어요)

2023-10-02 09:06 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +            not: 'ACCEPTED',
넵 멱등성땜에 이렇게 만든거 맞아요!

2023-10-04 10:40 UTC, devunt requested changes

2023-10-04 10:40 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +        where: { email: input.email },
P1: 외부에서 들어온 email 을 db에 쿼리할 때는 늘 `.toLowerCase()` 호출 필요

2023-10-04 10:40 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +            receivedEmail: input.email,
P1: 마찬가지로 `.toLowerCase()` 호출 필요

2023-10-04 10:40 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +      const existingInvitation = await db.spaceMemberInvitation.findUnique({
P4: 여기도 존재 여부만 확인하는거라면 `.exists` 써도 될 듯...?

2023-10-04 10:40 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +        const inviteeMember = await db.spaceMember.findFirst({
P4: 존재 여부만 확인하는거라면 `.exists` 써도 될 듯...?

2023-10-04 10:40 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +          role: 'MEMBER',
P3: 저희 피그마에는 멤버 초대할 때 권한을 지정해서 초대할 수 있게 UI가 되어있던데 요거 개발 스펙에도 반영 하는건지 확인 필요해 보여요

2023-10-06 10:25 UTC, devunt approved these changes

2023-10-06 10:32 UTC, merged