댓글 gql
penxle/penxle pull request #1384
Opened 2024-02-20 08:06 UTC by robin-maki

2024-02-20 08:06 UTC, robin-maki commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/penxle/penxle/1384?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1376** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1376?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1384** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1384?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/1384?utm_source=stack-comment).

2024-02-23 06:08 UTC, devunt requested changes

2024-02-23 06:08 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
> +  const updateCommentInput = builder.inputType('UpdateCommentInput', {
P1: 첫글자 대문자

2024-02-23 06:08 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
> +            // TODO: 댓글 허용 포스트인지?
P3: 요거 왜 TODO인지?!

2024-02-23 06:08 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
> +      type: 'Post',
P2: `PostComment` 를 리턴해야 할 듯?

2024-02-23 06:08 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
> +      type: 'Post',
P2: `PostComment` 를 리턴해야 할 듯?

2024-02-23 06:08 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
> +        });
P2: update 한 결과 그대로 리턴해도 될 듯

2024-02-23 06:08 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
> +      resolve: async (_, __, { input }, { db, ...context }) => {
P1: 첫번째 인자 써야 할 듯? (`query`)

2024-02-23 06:08 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
> +      content: t.string(),
P4: 우리 공개 댓글을 비공개로 바꾼다거나 하는건 안 되나요? 기획 논의 필요

2024-02-23 06:59 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
> +      content: t.string(),
일단 지금 논의에서는 빠져 있었고요 (정확히는 논의하지 않은 것에 가깝겠지만...) 사실 필요성도 잘 모르겠어요 저는 솔직히 익명인데 비밀댓글의 필요성도 부족하다고 생각하긴 한데... ㅁㄴㅇㄹ

2024-02-23 07:19 UTC, devunt approved these changes

2024-02-23 07:25 UTC, merged