마케팅 수신 동의 토스트 메시지 길이 줄임
penxle/penxle pull request #144
Opened 2023-09-30 02:39 UTC by devunt

2023-09-30 02:39 UTC, devunt commented
Current dependencies on/for this PR:
* main
  * **PR #144** <a href="https://app.graphite.dev/github/pr/penxle/penxle/144" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/144?utm_source=stack-comment).

2023-10-02 03:30 UTC, robin-maki requested changes

2023-10-02 03:30 UTC, robin-maki commented on apps/penxle.com/src/routes/(default)/me/accounts/+page.svelte
> +        });
P1:
> 정보통신망 이용촉진 및 정보보호 등에 관한 법률 시행령 
> 제62조의2(수신동의 등 처리 결과의 통지) 법 제50조 제7항에 따라 전자적 전송매체를 이용하여 영리목적의 광고성 정보를 전송하려는 자는 수신자가 수신동의, 수신거부 또는 수신동의 철회 의사를 표시한 날부터 14일 이내에 다음 각 호의 사항을 해당 수신자에게 알려야 한다.
> 1. 전송자의 명칭
> 2. 수신자의 수신동의, 수신거부 또는 수신동의 철회 사실과 해당 의사를 표시한 날짜
> 3. 처리 결과

라서 너무 길어도 전송자의 명칭 펜슬이 들어가야 해요 ㅜㅜ

2023-10-02 07:19 UTC, robin-maki approved these changes

2023-10-02 08:32 UTC, merged