pandacss 토큰 정리 및 escape hatch 최대한 줄이기
penxle/penxle pull request #1514
Opened 2024-03-09 06:14 UTC by devunt

2024-03-09 06:14 UTC, devunt commented
* **#1514** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1514?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @devunt and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-12 04:48 UTC, Seohyun-Roh requested changes

2024-03-12 04:48 UTC, Seohyun-Roh commented on apps/penxle.com/src/styles/colors.ts
> -  },
P2: 여기 새롭게 추가된 색인데 안쓰고 기존 색상으로 쓰나요..? 그럼 컬러 hex code 업데이트해야할 것 같아요

2024-03-15 03:28 UTC, Seohyun-Roh approved these changes

2024-03-15 03:33 UTC, merged