정기 출금 관련 gql
penxle/penxle pull request #1547
Opened 2024-03-15 07:13 UTC by robin-maki

2024-03-15 07:13 UTC, robin-maki commented
* **#1547** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1547?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @robin-maki and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-15 09:58 UTC, devunt requested changes

2024-03-15 09:58 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/revenue.ts
> +        if (dayjs().day() === 10) throw new IntentionalError('매월 10일에는 자동 출금 설정을 변경할 수 없어요');
P2: `dayjs.kst()` ?

2024-03-15 09:58 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/revenue.ts
> +        if (dayjs().day() === 10) throw new IntentionalError('매월 10일에는 자동 출금 설정을 변경할 수 없어요');
P2: `dayjs.kst()` ¿

2024-03-18 10:13 UTC, devunt approved these changes

2024-03-19 03:31 UTC, merged