나의 펜슬 경로, 레이아웃 변경
penxle/penxle pull request #184
Opened 2023-10-10 18:23 UTC by Seohyun-Roh

2023-10-10 18:23 UTC, Seohyun-Roh commented
Current dependencies on/for this PR:
* main
  * **PR #184** <a href="https://app.graphite.dev/github/pr/penxle/penxle/184" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/184?utm_source=stack-comment).

2023-10-11 06:56 UTC, devunt requested changes

2023-10-11 12:54 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/(default)/me/+layout.svelte
> +                $page.url.pathname === '/me/settings' && 'bg-primary text-primary',
수정했습니당

2023-10-17 10:04 UTC, devunt approved these changes

2023-10-17 10:07 UTC, merged