스페이스 나가기 gql
penxle/penxle pull request #185
Opened 2023-10-11 05:59 UTC by robin-maki

2023-10-11 05:59 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #183** <a href="https://app.graphite.dev/github/pr/penxle/penxle/183" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #185** <a href="https://app.graphite.dev/github/pr/penxle/penxle/185" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/185?utm_source=stack-comment).

2023-10-11 06:29 UTC, devunt requested changes

2023-10-11 06:29 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +      await db.spaceMember.delete({
P1:

스페이스 멤버가 나갈 때 hard delete 대신 soft delete를 하는게 맞아보여요.
이유: 포스트 작성자의 스페이스 전용 프로필을 보여주고, 전용 프로필을 지우거나 삭제했을 때 전체 포스트에 쉽게 반영하려면 Post에 작성자가 `users.id`가 아닌 `space_members.id` 로 외래키가 걸려야 할 것 같고, 그렇게 된다면 스페이스를 나갈 때 스페이스 멤버 테이블을 지울 수도 없고 지워서도 안 될 듯...?!

스페이스 나가더라도 멤버를 hard delete하는게 아니라 soft delete하게 변경하고, gql의 `User.spaces`나 `Space.members`, 스페이스 멤버 초대쪽 로직에 다 반영하는게 맞을 듯...?!

2023-10-11 06:29 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +  kickSpaceMember: t.withAuth({ user: true }).field({
P4: `removeSpaceMember` 같은 이름은 어떨까용

2023-10-11 06:29 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +  leaveSpace: t.withAuth({ user: true }).field({
P5: space member에 관련된된거라 요거 mutation 이름도 통일감 있게 `spaceMember` 가 들어가면 좋겠는데 마땅한 이름이 생각이 안 나네요... 지금 `leaveSpace` 이름도 괜찮아보여서 더 고민됩니다

2023-10-11 06:29 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +    profileId: t.id(),
P2: 요거 그냥 `spaceMemberId` 하나만 받아와도 될 거 같아요 !!

2023-10-11 07:42 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +  leaveSpace: t.withAuth({ user: true }).field({
저도 `leaveSpace` 외에 더 좋은 이름을 아직 못 찾겠어요...

2023-10-11 13:51 UTC, devunt requested changes

2023-10-11 13:51 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +      }),
P2: `query: { where: { state: 'ACTIVE' } }` 로 바꿀 수 있을 것 같아요

2023-10-11 13:51 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> -  @@unique([spaceId, userId])
P3: 요거 unique는 왜 빠졌는지 궁금해요! 스페이스 재가입하면 `INACTIVE`를 `ACTIVE`로 돌리는게 맞지 않나 싶기도... (예전에 자기가 썼던 글들의 소유권을 다시 다 가져올 수 있어야 하는거 아닌가? 싶은 기분)

2023-10-11 13:51 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
>            role: 'ADMIN',
P1: `state: 'ACTIVE'` 체크 필요

2023-10-11 13:51 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +          role: 'MEMBER',
P3: 여기서 `role`도 강제로 멤버로 업데이트하는 이유가 있을까용 👀

2023-10-11 13:51 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +    nullable: true,
P2: 방금 inactive로 바꾼 `SpaceMember`를 리턴하는게 맞는 듯 !!

2023-10-11 13:51 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +    nullable: true,
P2: 방금 inactive로 바꾼 `SpaceMember`를 리턴하는게 맞는 듯 !!

2023-10-12 04:50 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +          role: 'MEMBER',
딱히 없긴 하네요...

2023-10-12 05:28 UTC, devunt approved these changes

2023-10-12 09:53 UTC, merged