스페이스 소개 탭 내용 채우기
penxle/penxle pull request #213
Opened 2023-10-18 06:29 UTC by x86chi

2023-10-18 06:30 UTC, x86chi commented
Current dependencies on/for this PR:
* main
  * **PR #194** <a href="https://app.graphite.dev/github/pr/penxle/penxle/194" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #203** <a href="https://app.graphite.dev/github/pr/penxle/penxle/203" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #213** <a href="https://app.graphite.dev/github/pr/penxle/penxle/213" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
      * **PR #208** <a href="https://app.graphite.dev/github/pr/penxle/penxle/208" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/213?utm_source=stack-comment).

2023-10-18 19:27 UTC, Seohyun-Roh requested changes

2023-10-18 19:27 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/(default)/[space]/about/+page.svelte
> +    class="subtitle-18-eb after:text-secondary after:ml-2 after:content-[attr(data-count)]"
P3: unocss의 variant group을 사용해보시는건 어떨까요?
https://unocss.dev/transformers/variant-group#variant-group-transformer

2023-10-18 19:27 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/(default)/[space]/about/+page.svelte
> +          <Badge class="caption-12-b ml-1" color="green">관리자</Badge>
P2: 디자인에서 폰트 크기 변경된게 적용이 안되어있었네요😢 텍스트 크기 설정은 컴포넌트 쪽에 들어가있는게 맞을것 같은데.. 같이 수정해주시면 감사하겠습니다

2023-10-18 19:27 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/(default)/[space]/about/+page.svelte
> +  <p class="bodylong-16-m">{$query.space.description ?? '아직 소개가 없습니다.'}</p>
P2: 저희 사이트 내 워딩을 다 ~해요체로 통일하기로 했는데요! 이부분 피그마에 코멘트달아놓았으니 수정사항 반영해주시면 될것같습니다

2023-10-18 19:33 UTC, Seohyun-Roh requested changes

2023-10-18 19:33 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/(default)/[space]/about/+page.svelte
> +<section class="p8 flex flex-col gap-3">
P5: `p8`로 써도 잘 동작하긴 하는데 그래도 최대한 통일해주는게 좋을 것 같아서 👀 `p-8`처럼 쓰는게 어떨까요..?

2023-10-19 02:28 UTC, x86chi reviewed
리뷰 주신 사항 반영했습니다!

2023-10-19 02:28 UTC, x86chi commented on apps/penxle.com/src/routes/(default)/[space]/about/+page.svelte
> +          <Badge class="caption-12-b ml-1" color="green">관리자</Badge>
```diff
<div
  class={clsx(
-    'flex center h-6 p-2.5 rounded text-3.25',
+    'flex center h-6 p-2.5 rounded caption-12-b',
```

a037c5df897df751bc67ae9c683b8ff03272c1b5: 의도하신 말이 뱃지 컴포넌트 사용하는 측에서 직접 폰트 지정을 빼고 기본 폰트를 `caption-12-b` 로 수정을 부탁하시는게 맞으실까요?

2023-10-19 03:45 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/(default)/[space]/about/+page.svelte
> +          <Badge class="caption-12-b ml-1" color="green">관리자</Badge>
네 맞습니다!!

2023-10-19 05:44 UTC, devunt requested changes

2023-10-19 05:44 UTC, devunt commented on apps/penxle.com/src/routes/(default)/[space]/about/+page.svelte
> +      {dayjs($query.space.createdAt).format('YYYY.MM.DD')}
P2: `dayjs().formatAsDate()` 함수가 있어요. 포맷이 `YYYY-MM-DD` 긴 한데, 요건 전체적으로 통일해야 하는게 맞을 것 같아서, 디자인쪽이랑도 얘기해서 둘 중 하나로 결정해야 할 듯?

2023-10-19 05:58 UTC, devunt commented on apps/penxle.com/src/routes/(default)/[space]/about/+page.svelte
> +      {dayjs($query.space.createdAt).format('YYYY.MM.DD')}
`formatAsDate()` 함수에 관련 변경사항 업데이트해두었어요

2023-10-19 06:12 UTC, devunt approved these changes

2023-10-19 06:13 UTC, merged