스페이스 팔로우 gql
penxle/penxle pull request #234
Opened 2023-10-23 03:48 UTC by robin-maki

2023-10-23 03:48 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #234** <a href="https://app.graphite.dev/github/pr/penxle/penxle/234" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/234?utm_source=stack-comment).

2023-10-25 02:30 UTC, devunt requested changes
P1: `followSpace` / `unfollowSpace` 는 `user.ts` 가 아니라 `space.ts` 에 들어가야 할 거 같아용

2023-10-25 02:30 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +    type: 'User',
P1: `Space` 를 리턴해야 할 듯

2023-10-25 02:30 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +        },
P5: (개인적으로) `where`를 제외한 딴 필드들은 한 줄로 쓰는걸 선호합니다

2023-10-25 02:30 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +          throw new NotFoundError();
P3: `PermissionDeniedError` ?

2023-10-25 02:30 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +      await db.userSpaceFollowing.upsert({
P5: 그냥 `create` 하는 것도? 정말 필요한거 아니면 굳이 API들을 다 idempotent하게 만들어야 하나 싶은 생각이 있네용

2023-10-25 02:30 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +    type: 'User',
P1: 마찬가지로 `Space` 리턴하도록

2023-10-25 02:30 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +      await db.userSpaceFollowing.deleteMany({
P5: 이거도 될 수 있으면 그냥 `delete` 하는게 어떨까 하는 생각 (팔로 안 하고 있는데 언팔하면 에러가 나야 하지 않나?)

2023-10-25 02:30 UTC, devunt commented on cspell.config.json
> +    "Unfollow",
P1: 전부 소문자로

2023-10-25 02:30 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +    followingSpaces: t.prismaField({
P2: `followedSpaces` 가 좀 더 문법적으로 맞을 것 같아요

2023-10-25 06:22 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +          throw new NotFoundError();
갠적으로는 프라이빗이면 아예 그런 스페이스의 존재 자체를 보여주지 말아야 한다고 생각하긴 했었는데 생각해보니 우리가 스페이스의 존재까지는 알려주고 있으니까 그런 것도 괜찮을 거 같아요!

2023-10-25 06:36 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +        },
사실 저는 2개 이상이면 줄을 나누는 걸 (개인적으로) 선호해서요...

2023-10-25 06:38 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +      await db.userSpaceFollowing.upsert({
인터넷이 느려서 팔로우/언팔로우 요청이 두번 간다던가 했을때 오류가 발생하는건 그다지 깔끔하지 않은 것 같아서요...

2023-10-25 11:11 UTC, devunt approved these changes

2023-10-25 11:34 UTC, devunt commented
### Merge activity

* **Oct 25, 7:34 AM**: @devunt started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/234).

2023-10-25 11:35 UTC, merged