스페이스 URL 설정 dnd 구현
penxle/penxle pull request #238
Opened 2023-10-24 02:55 UTC by Seohyun-Roh

2023-10-24 02:55 UTC, Seohyun-Roh commented
Current dependencies on/for this PR:
* main
  * **PR #234** <a href="https://app.graphite.dev/github/pr/penxle/penxle/234" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #235** <a href="https://app.graphite.dev/github/pr/penxle/penxle/235" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #238** <a href="https://app.graphite.dev/github/pr/penxle/penxle/238" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/238?utm_source=stack-comment).

2023-10-24 12:00 UTC, devunt approved these changes

2023-10-25 10:07 UTC, x86chi commented on apps/penxle.com/src/routes/(default)/[space]/(setting)/settings/(index)/+page.svelte
> +    const indexTarget = links.findIndex((i) => i == link);
```suggestion
    const indexDragged = links.indexOf(draggedItem);
    const indexTarget = links.indexOf(link);
```

P3: 값 자체를 비교할 경우 predicate function 보단 [`Array.propotype.indexOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf) 가 바람직하다고 생각합니다.

2023-10-26 08:25 UTC, x86chi requested changes
> Uncaught Error: Function called outside component initialization

P1: Safari 와 FireFox 에서 링크 추가 시 위 오류가 나고 있어 해결이 필요합니다! 

`links` 아이템이 늘어날 때마다 컴포넌트 생애주기 바깎에서 호출된다고 알려주고 있고, 오류 스택 트레이스를 보니 `$lib/form` 의 `createMutationForm` 내부 코드로 확인했습니다.

```
get_current_component lifecycle.js:11
    setContext lifecycle.js:127
    context context.ts:32
    callExtender create-form-action.ts:81
```

| Safari | FireFox |
| :--: | :--: |
| ![스크린샷 2023-10-26 오후 5.18.02.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/8hvfTZ24DHo9E1Ato9YP/b394264d-bd2d-4f3f-a7ca-73e3ad9b1ef3.png) | ![스크린샷 2023-10-26 오후 5.19.10.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/8hvfTZ24DHo9E1Ato9YP/4a9bb95d-a413-4c6f-a679-c51e28de9856.png) |

2023-11-01 06:46 UTC, devunt requested changes

2023-11-01 06:46 UTC, devunt commented on cspell.config.json
> +    "sortablejs",
P1: 요거 다시 빼주세요

2023-11-02 02:46 UTC, robin-maki commented
참고로... 전에 오프라인에서 한 논의에 따라 스페이스의 `externalLinks` 필드가 `SpaceExternalLink[]`를 리턴하게 바뀌었어요 😅 https://github.com/penxle/penxle/pull/235#discussion_r1379529229

2023-11-02 04:38 UTC, x86chi commented on apps/penxle.com/src/routes/(default)/[space]/dashboard/settings/+page.svelte
> +              <TextInput class="w-full" placeholder="URL을 입력해주세요" bind:value={link} />
P3: <TextInput /> 에 `id` 와 `type="url"` 어트리뷰트 추가를 웬만하면 반영해주세요!

```suggestion
              <label class="body-13-b" for={`url${index + 1}`}>{`URL ${index + 1}`}</label>
              <TextInput id={`url${index + 1}`} type="url" class="w-full" placeholder="URL을 입력해주세요" bind:value={link} />
```

2023-11-02 04:45 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/(default)/[space]/dashboard/settings/+page.svelte
> +              <TextInput class="w-full" placeholder="URL을 입력해주세요" bind:value={link} />
올렸다고 생각했는데 안올라가있었네요..! 수정했습니다 :)

2023-11-02 04:50 UTC, x86chi commented on apps/penxle.com/src/routes/(default)/[space]/dashboard/settings/+page.svelte
> +              <TextInput class="w-full" placeholder="URL을 입력해주세요" bind:value={link} />
P4: `autocomplete` 어트리뷰트도 달아주시면 이전에 사용자가 브라우저에 입력한 URL 정보를 재사용할 수 있어 편하지 않을까 싶네요..!

2023-11-02 07:47 UTC, x86chi requested changes

2023-11-02 07:47 UTC, x86chi commented on apps/penxle.com/src/lib/components/forms/TextInput.svelte
>      type="text"
P2: `autocomplete` 을 컴포넌트 파일에서 하드코딩을 제가 제안한 게 아니라 사용하는 곳에서 `autocomplete` 어트리뷰트를 넣어달라는 의견이었어요!

2023-11-02 08:32 UTC, Seohyun-Roh commented on apps/penxle.com/src/lib/components/forms/TextInput.svelte
>      type="text"
앗 네 그럼 input마다 `autocomplete="url"`처럼 따로 값을 지정해달라는 말씀이신가요? 따로 지정안해줘도 autocomplete의 default value가 on인걸로 알고있어서요..!

2023-11-03 02:36 UTC, x86chi commented on apps/penxle.com/src/lib/components/forms/TextInput.svelte
>      type="text"
아뇨! 어트리뷰트 값은 말해주신 내용 같이 필요하지 않습니다. 이미 지정한 type 어트리뷰트 값을 통해 브라우저가 자동으로 어떤 포멧으로 자동완성을 할지 스스로 판단해줘요.

autocomplete 옵션이 모든 input 마다 넣기에는 input type=text 같이 입력에 들어가는 형식이 광범위하다는 문제가 있어 URL 이나 우편번호, 전화번호 형식 같이 특수한 경우에만 권해드립니다.

2023-11-06 03:23 UTC, x86chi commented on apps/penxle.com/src/routes/(default)/[space]/dashboard/settings/+page.svelte
> +    });
```js
onMount(() => {
// 마운트 로직
return () => {
  // 언마운트 로직
  }
})
```

P3: 한 기능에 대해 onMount 하고 onDestory 가 같이 쓰인다면 언마운트 로직을 onMount 인자의 리턴 함수 안에 넣는게 `sortable` 변수 값을 바깎에다 정의할 필요 없이 해당 함수 안의 상수로 유지할 수 있게 되서 더 관리하기 편하다고 생각합니다!

2023-11-09 05:50 UTC, x86chi approved these changes

2023-11-29 14:01 UTC, devunt approved these changes

2023-11-29 14:10 UTC, merged