내 글만 보기 필터 gql
penxle/penxle pull request #242
Opened 2023-10-24 07:38 UTC by robin-maki

2023-10-24 07:39 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #211** <a href="https://app.graphite.dev/github/pr/penxle/penxle/211" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #196** <a href="https://app.graphite.dev/github/pr/penxle/penxle/196" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #216** <a href="https://app.graphite.dev/github/pr/penxle/penxle/216" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #242** <a href="https://app.graphite.dev/github/pr/penxle/penxle/242" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
        * **PR #205** <a href="https://app.graphite.dev/github/pr/penxle/penxle/205" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #209** <a href="https://app.graphite.dev/github/pr/penxle/penxle/209" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #204** <a href="https://app.graphite.dev/github/pr/penxle/penxle/204" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #207** <a href="https://app.graphite.dev/github/pr/penxle/penxle/207" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #202** <a href="https://app.graphite.dev/github/pr/penxle/penxle/202" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #192** <a href="https://app.graphite.dev/github/pr/penxle/penxle/192" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #193** <a href="https://app.graphite.dev/github/pr/penxle/penxle/193" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #198** <a href="https://app.graphite.dev/github/pr/penxle/penxle/198" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/242?utm_source=stack-comment).

2023-11-11 09:19 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +      args: { myPostOnly: t.arg.boolean({ defaultValue: false }) },
P3: 인자 이름 `mine` 은 어떨까용

2023-11-12 12:21 UTC, devunt requested changes

2023-11-12 12:21 UTC, devunt commented on apps/penxle.com/schema.graphql
> +  posts(myPostOnly: Boolean! = false): [Post!]!
P1: 스키마 파일 재생성해주세요...! 요거 vite 플러그인으로 어케 알아서 잘 되게 못 만드나... 나중에 시간 될 때 한번 보기로

2023-11-12 17:31 UTC, devunt approved these changes

2023-11-12 17:34 UTC, merged