게시물 저장 뮤테이션 savePost로 일원화
penxle/penxle pull request #251
Opened 2023-10-26 04:05 UTC by robin-maki

2023-10-26 04:05 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #251** <a href="https://app.graphite.dev/github/pr/penxle/penxle/251" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/251?utm_source=stack-comment).

2023-10-26 04:25 UTC, x86chi requested changes
P1: 썸네일 외에 빠트리신 부분으로 커버 이미지 (`coverImageId`, `coverImage`) 입력 필드를 추가 부탁드릴게요!

2023-10-26 04:25 UTC, x86chi commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +          state: input.revisionKind === 'PUBLISHED' ? 'PUBLISHED' : undefined,
P5: 백엔드 문법에 사소하게 궁금한 사항인데 create 에서는 임시저장 포스팅에 대해 `'DRAFT'` 로 설정하는 걸 update 에서는 `undefiend` 로 하는 이유가 뭔지 궁금합니다.

2023-10-26 04:27 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +          state: input.revisionKind === 'PUBLISHED' ? 'PUBLISHED' : undefined,
이미 발행된 포스트를 수정 들어가서 임시저장 했다고 그 포스트가 발행 전 상태가 되면 안되니까요...?

2023-10-26 04:32 UTC, x86chi commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +          state: input.revisionKind === 'PUBLISHED' ? 'PUBLISHED' : undefined,
엇 그러면 발행된 포스트에 대해 임시저장과 재발행을 어떻게 서버에서 구분하는지 궁금합니다! 혹시 임시저장 기능 없이 바로 재발행이 되는 건가요?

2023-10-26 04:36 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +          state: input.revisionKind === 'PUBLISHED' ? 'PUBLISHED' : undefined,
발행된 포스트의 경우에도 `revisionKind`를 `AUTO_SAVE` 같은 걸루 주면 임시저장이 되고 (포스트는 발행 상태여도 그 리비전이 임시저장 상태라서요) `PUBLISHED`로 주면 재발행이 되는거구 그런 식이죠...?

2023-10-26 04:44 UTC, x86chi approved these changes

2023-10-26 06:52 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +        thumbnailBounds: input.thumbnailBounds || undefined,
P3: 될 수 있으면 `||` 보다는 `??` 사용을 권장합니당

2023-10-26 06:52 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
>      type: PostDraft,
P5: 아주 사소한건데.... `savePost` 에서 `PostDraft` 를 리턴하는게 살짝 이상한 느낌....?! (전에는 `draftPost`에서 `PostDraft` 를 리턴하니까 뭔가 아다리가 맞았는데 지금은 시맨틱적으로 조금 안 맞는 느낌.....?! `savePost` 이름을 바꾸거나 `PostDraft` 이름을 바꾸거나 해도 괜찮을 거 같아요 (근데 아주 사소한거라 안 바꿔도 상관은 없을 듯)

2023-10-26 07:03 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
>      type: PostDraft,
아예 다시 `Post`랑 `PostDraft`를 합칠까요...? 지금은 `space`가 필수인 구조다 보니까 가능할거같은데...

2023-10-27 06:15 UTC, devunt approved these changes

2023-10-27 06:30 UTC, robin-maki commented
### Merge activity

* **Oct 27, 2:30 AM**: @robin-maki started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/251).

2023-10-27 06:30 UTC, merged