포스트 옵션 수정 gql
penxle/penxle pull request #255
Opened 2023-10-26 06:57 UTC by robin-maki

2023-10-26 06:57 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #251** <a href="https://app.graphite.dev/github/pr/penxle/penxle/251" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #252** <a href="https://app.graphite.dev/github/pr/penxle/penxle/252" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #255** <a href="https://app.graphite.dev/github/pr/penxle/penxle/255" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/255?utm_source=stack-comment).

2023-10-26 07:47 UTC, devunt requested changes

2023-10-26 07:47 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +    visibility: t.field({ type: PostVisibility }),
P1: `visibility`도 `required: false` 적용 부탁드려용

2023-10-27 06:17 UTC, devunt approved these changes

2023-10-27 06:22 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +          option: { update: { ...defaultOptions } },
포스트가 업데이트될때는 이거 수정하면 안되네요!!!!!

2023-10-27 06:22 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +          option: { update: { ...defaultOptions } },
셀프로는 request change 못 하네요... 암튼 머지하지 말구 잠시만 기다려주세요...

2023-10-27 06:30 UTC, robin-maki commented
### Merge activity

* **Oct 27, 2:30 AM**: @robin-maki started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/255).

2023-10-27 06:37 UTC, merged