스페이스 포스트 관리 페이지
penxle/penxle pull request #275
Opened 2023-10-30 10:25 UTC by x86chi

PopupSearch UI 컴포넌트화하기

컬렉션 관리 페이지의 검색 UI를 추가하면서 멤버 관리 페이지에 쓰인 UI와 공통 요소로 확인을 하여 컴포넌트화를 했습니다.

스페이스 포스트 관리 페이지 구성하기

Button red color 추가하기

날짜 필터링 모달 구현 중

2023-10-30 10:25 UTC, x86chi commented
Current dependencies on/for this PR:
* main
  * **PR #260** <a href="https://app.graphite.dev/github/pr/penxle/penxle/260" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #275** <a href="https://app.graphite.dev/github/pr/penxle/penxle/275" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/275?utm_source=stack-comment).

2023-11-24 15:52 UTC, x86chi commented
기능 테스트 시 #490 프리뷰를 참고 부탁드립니다.

2023-11-26 09:11 UTC, Seohyun-Roh requested changes

2023-11-26 09:11 UTC, Seohyun-Roh commented on apps/penxle.com/src/lib/components/pages/PostManageTable.svelte
> +      class="inline-flex gap-1 flex-justify-between items-center px-6 py-2 max-w-40.375rem w-full flex-wrap fixed bottom-7.25rem
P2: 프리뷰 확인해보니 하단 메뉴바가 너무 위에 떠있는 것 같습니다..!

<img width="778" alt="image" src="https://github.com/penxle/penxle/assets/76952602/d0638b5a-bbf5-4c78-9881-a753d6930906">

2023-11-26 09:11 UTC, Seohyun-Roh commented on apps/penxle.com/src/lib/components/pages/PostManageTable.svelte
> +        <Button color="red" size="md" on:click={() => deletePosts(_selectedPostIds)}>삭제하기</Button>
P2: 여기서도 삭제하기 전에 한번 확인하는 모달 띄워주면 좋을 것 같습니다.
그리고 선택한 포스트들이 삭제되었는데도 체크한 포스트 갯수가 그대로 남아있는데 이부분 확인하시고 수정 부탁드립니다!

2023-11-26 09:11 UTC, Seohyun-Roh commented on apps/penxle.com/src/lib/components/pages/PostManageTable.svelte
> +            external
포스트 수정할 때 새창으로 띄우는게 더 좋을까요..??

2023-11-26 09:11 UTC, Seohyun-Roh commented on apps/penxle.com/src/lib/components/pages/PostManageTable.svelte
> +        posts @_required {
P2: 저희 fragment이름은 컨벤션이 `컴포넌트명(or 페이지/레이아웃)_타입`이라서 `PostManageTable_Space`로 이름을 수정하면 좋을 것 같아요.

2023-11-26 09:11 UTC, Seohyun-Roh commented on apps/penxle.com/src/lib/components/pages/PostManageTable.svelte
> +      fragment PostManageTableComponent_SpaceMember_query on SpaceMember {
P3: 여기도 `PostManageTable_SpaceMember` 정도로 수정하면 좋을 것 같습니다.

2023-11-27 07:13 UTC, x86chi commented on apps/penxle.com/src/lib/components/pages/PostManageTable.svelte
> +            on:click={() => deletePost({ postId: post.id })}
표 UI 에서 삭제할 때마다 경고 팝업이 뜨는 건 피로함을 주는 것 같아 적용하지 않은게 좋다고 생각합니다.

2023-11-27 10:14 UTC, robin-maki commented on apps/penxle.com/src/lib/components/pages/PostManageTable.svelte
> +            on:click={() => deletePost({ postId: post.id })}
글 일괄 삭제 같은 행동이 그다지 많이 일어날 동작은 아니기도 하고 꽤 위험한 동작이니까 저는 확인해주는게 좀 더 좋을 거 같아요...!

2023-11-27 12:39 UTC, x86chi commented on apps/penxle.com/src/lib/components/pages/PostManageTable.svelte
> +            external
context 에 따라 새창으로 열리고 이동하는 걸 자동으로 한다면 사용자 입장에 암시적으로 느껴 불편하다고 생각해요!

2023-11-28 10:54 UTC, x86chi commented on apps/penxle.com/src/lib/components/pages/PostManageTable.svelte
> +            on:click={() => deletePost({ postId: post.id })}
반영했습니다~ 리뷰 부탁드릴게요!

2023-11-28 10:57 UTC, Seohyun-Roh commented on apps/penxle.com/src/lib/components/pages/PostManageTable.svelte
> +      <TableData></TableData>
이부분은 왜 들어가있는건가요?.?

2023-11-28 12:03 UTC, x86chi commented on apps/penxle.com/src/lib/components/pages/PostManageTable.svelte
> +      <TableData></TableData>
모바일 화면 너비에서 마지막에 빈 테이블 헤드 요소가 없으면 테이블 헤더 오른쪽이 잘리는 문제가 있어서 추가했습니다.

> https://github.com/penxle/penxle/blob/1bd4639d/apps/penxle.com/src/lib/components/pages/PostManageTable.svelte#L231C20-L232 참고

2023-11-28 12:04 UTC, Seohyun-Roh approved these changes

2023-11-28 12:47 UTC, merged