스페이스 포스트 목록
penxle/penxle pull request #282
Opened 2023-10-30 13:22 UTC by x86chi

2023-10-30 13:22 UTC, x86chi commented
Current dependencies on/for this PR:
* main
  * **PR #282** <a href="https://app.graphite.dev/github/pr/penxle/penxle/282" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/282?utm_source=stack-comment).

2023-11-07 03:17 UTC, Seohyun-Roh requested changes

2023-11-07 03:17 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/(default)/[space]/(space)/(index)/+page.svelte
> +            thumbnail {
P4: 이런 경우 엔터를 한번 넣어주시면 너무 좋을 것 같고.. id도 같이 쿼리해주면 좋을 것 같습니다

2023-11-07 03:17 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/(default)/[space]/(space)/(index)/+page.svelte
> +          class="flex-grow line-height-162.5% bodylong-16-m text-secondary overflow-hidden line-clamp-6"
P3: line-height는 이미 bodylong에 적용되어있어서 빼도 될 것 같습니다

2023-11-07 03:17 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/(default)/[space]/(space)/(index)/+page.svelte
> +      class="flex flex-col gap-2 w-full p-6 bg-cardprimary border-(secondary solid 0.0625rem) rounded-2xl <sm:(border-none rounded-none)"
P3: border 스타일이 디자인과 다른 것 같아요..!

2023-11-07 11:02 UTC, Seohyun-Roh approved these changes

2023-11-08 09:41 UTC, merged