포스트 링크 공유
penxle/penxle pull request #295
Opened 2023-10-31 14:44 UTC by robin-maki

2023-10-31 14:45 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #261** <a href="https://app.graphite.dev/github/pr/penxle/penxle/261" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #263** <a href="https://app.graphite.dev/github/pr/penxle/penxle/263" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #293** <a href="https://app.graphite.dev/github/pr/penxle/penxle/293" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #265** <a href="https://app.graphite.dev/github/pr/penxle/penxle/265" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #295** <a href="https://app.graphite.dev/github/pr/penxle/penxle/295" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
          * **PR #294** <a href="https://app.graphite.dev/github/pr/penxle/penxle/294" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/295?utm_source=stack-comment).

2023-11-06 03:00 UTC, devunt requested changes

2023-11-06 03:00 UTC, devunt commented on apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
> +    const shortLink = `pnxl.me/${$query.post.shortlink}`;
P1: 앞에 `https://` 붙여주세용

2023-11-06 03:01 UTC, devunt requested changes
P1: 커밋 메시지에 엉뚱한게 들어있는 거 같은데 커밋 메시지도 수정해주세요...!

2023-11-06 05:50 UTC, devunt approved these changes

2023-11-06 11:27 UTC, merged