포스트 트리거 워닝 gql
penxle/penxle pull request #310
Opened 2023-11-03 08:22 UTC by robin-maki

2023-11-03 08:22 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #310** <a href="https://app.graphite.dev/github/pr/penxle/penxle/310" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/310?utm_source=stack-comment).

2023-11-05 04:11 UTC, devunt requested changes

2023-11-05 04:11 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +          },
P2: 컨텐츠 필터 업데이트는 `revisePost`가 아니라 `updatePostOptions` 에 들어가야 하지 않을까요?! (리비전에 붙는 정보가 아니니까...?!)

2023-11-05 07:14 UTC, devunt approved these changes

2023-11-05 14:17 UTC, merged