포스트 트리거 워닝 보여주기
penxle/penxle pull request #321
Opened 2023-11-06 07:31 UTC by x86chi

2023-11-06 07:32 UTC, x86chi commented
Current dependencies on/for this PR:
* main
  * **PR #321** <a href="https://app.graphite.dev/github/pr/penxle/penxle/321" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/321?utm_source=stack-comment).

2023-11-10 05:52 UTC, Seohyun-Roh requested changes

2023-11-10 05:52 UTC, Seohyun-Roh commented on cspell.config.json
> +    "PTSD"
P2: cspell이 대소문자 구분도 하나요..? 상관없다면 소문자, 알파벳 순서로 위치시키는게 좋을 것 같습니다.

2023-11-14 05:26 UTC, Seohyun-Roh requested changes
일단 restack 부탁드립니다!
그리고 글 내용이 짧을 경우 블러 부분 레이아웃이 깨지는 문제가 있는 것 같아요.

<img width="782" alt="image" src="https://github.com/penxle/penxle/assets/76952602/d85a43c6-cacd-41e8-bf9c-3b18f9c1c3d1">

2023-11-14 08:36 UTC, Seohyun-Roh approved these changes

2023-11-14 10:19 UTC, merged