포스트 글자수 gql
penxle/penxle pull request #333
Opened 2023-11-07 14:29 UTC by robin-maki

2023-11-07 14:30 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #331** <a href="https://app.graphite.dev/github/pr/penxle/penxle/331" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #333** <a href="https://app.graphite.dev/github/pr/penxle/penxle/333" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/333?utm_source=stack-comment).

2023-11-08 08:54 UTC, x86chi requested changes

2023-11-08 08:54 UTC, x86chi commented on apps/penxle.com/schema.graphql
#331 작업이 여기에도 있는데 정리 부탁드릴게요!

2023-11-08 09:59 UTC, robin-maki commented on apps/penxle.com/schema.graphql
정확히 어떤 말씀이실까요...? `HIDE` 빼는거라면 이미 반영되어 있어요

2023-11-08 10:00 UTC, devunt approved these changes

2023-11-08 10:02 UTC, merged