이모지 종류 추가 및 트위모지로 변경
penxle/penxle pull request #343
Opened 2023-11-08 19:27 UTC by Seohyun-Roh

2023-11-08 19:27 UTC, Seohyun-Roh commented
Current dependencies on/for this PR:
* main
  * **PR #343** <a href="https://app.graphite.dev/github/pr/penxle/penxle/343" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/343?utm_source=stack-comment).

2023-11-09 01:16 UTC, devunt requested changes

2023-11-09 01:16 UTC, devunt commented on apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
> +      {#each $query.post.reactions.slice(0, 30) as reaction (reaction)}
P2: each key로 `reaction.id` 를 쓰는게 더 나아보여요!

2023-11-09 01:16 UTC, devunt commented on apps/penxle.com/src/routes/(default)/[space]/[post]/+page.svelte
> +          {#each $query.post.reactions.slice(30) as reaction (reaction)}
P2: 여기도!

2023-11-09 04:38 UTC, devunt approved these changes

2023-11-09 04:43 UTC, merged