태그 숨기기 gql
penxle/penxle pull request #344
Opened 2023-11-10 04:05 UTC by robin-maki

2023-11-10 04:05 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #330** <a href="https://app.graphite.dev/github/pr/penxle/penxle/330?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #344** <a href="https://app.graphite.dev/github/pr/penxle/penxle/344?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/344?utm_source=stack-comment).

2023-11-11 09:13 UTC, devunt requested changes

2023-11-11 09:13 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/tag.ts
> +    tag: t.string(),
P2: 요거 `tagId` 를 받는게 맞는 거 같아요

2023-11-11 09:13 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/tag.ts
> +    tag: t.string(),
P2: 요거 `tagId` 를 받는게 맞는 거 같아요

2023-11-11 09:13 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/tag.ts
> +    type: 'Void',
P1: `Tag`를 리턴해야 하지 않나... 싶기도? `Void` 타입은 최대한 사용을 자제하는게 맞을 거 같아요

2023-11-11 09:13 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/tag.ts
> +    type: 'Void',
P1: `Tag`를 리턴해야 하지 않나... 싶기도? `Void` 타입은 최대한 사용을 자제하는게 맞을 거 같아요

2023-11-11 09:13 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
>  model UserTagPreference {
P2: 요거 UserTagMute` 로 바꾸고 `type`을 빼는게 나을 거 같기도...

2023-11-12 12:25 UTC, merged