포스트 비밀번호 gql
penxle/penxle pull request #349
Opened 2023-11-10 07:36 UTC by robin-maki

2023-11-10 07:36 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #349** <a href="https://app.graphite.dev/github/pr/penxle/penxle/349?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/349?utm_source=stack-comment).

2023-11-12 04:49 UTC, devunt requested changes

2023-11-12 04:49 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +  unlockPasswordedpost: t.prismaField({
P1: Post 대문자로 해주세요

2023-11-12 04:49 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +          throw new PermissionDeniedError();
P2: UI에서 에러 띄워줄거 생각하면 `FormValidationError` 가 나은 듯?

2023-11-12 20:59 UTC, devunt approved these changes

2023-11-12 21:03 UTC, merged