포스트 최종 저장 시간 표시
penxle/penxle pull request #352
Opened 2023-11-10 13:44 UTC by Seohyun-Roh

2023-11-10 13:44 UTC, Seohyun-Roh commented
Current dependencies on/for this PR:
* main
  * **PR #351** <a href="https://app.graphite.dev/github/pr/penxle/penxle/351?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #352** <a href="https://app.graphite.dev/github/pr/penxle/penxle/352?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/352?utm_source=stack-comment).

2023-11-13 08:33 UTC, devunt requested changes
restack 해주세요

2023-11-15 06:45 UTC, x86chi commented on apps/penxle.com/src/lib/components/Tooltip.svelte
> +  export let message = '';
툴팁 메시지 기본값을 넣으신 이유가 뭔지 궁금합니다.

2023-11-15 07:01 UTC, Seohyun-Roh commented on apps/penxle.com/src/lib/components/Tooltip.svelte
> +  export let message = '';
message를 prop이 아닌 slot을 통해 넘겨줄 경우 기본값을 지정해주지 않으면 에러 메시지가 떠서 기본값을 지정해주었습니다

2023-11-15 14:01 UTC, devunt approved these changes

2023-11-15 14:58 UTC, x86chi approved these changes

2023-11-19 17:26 UTC, closed without merging