구분선 기능 구현
penxle/penxle pull request #363
Opened 2023-11-12 19:05 UTC by x86chi

2023-11-12 19:05 UTC, x86chi commented
Current dependencies on/for this PR:
* main
  * **PR #363** <a href="https://app.graphite.dev/github/pr/penxle/penxle/363?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/363?utm_source=stack-comment).

2023-11-13 08:31 UTC, devunt requested changes

2023-11-13 08:31 UTC, devunt commented on apps/penxle.com/src/lib/tiptap/nodes/horizontal-rule.ts
> +      level: {
P2: 구분선 종류인데 `level`이 아니지 않을까요...?!

2023-11-13 08:31 UTC, devunt commented on apps/penxle.com/src/lib/tiptap/nodes/horizontal-rule.ts
> +  },
P2: 저희 input rule은 안 씁니다! (무조건 명시적으로 삽입)

2023-11-14 10:58 UTC, devunt approved these changes

2023-11-14 11:02 UTC, merged