태그 팔로우 gql
penxle/penxle pull request #371
Opened 2023-11-14 06:48 UTC by robin-maki

2023-11-14 06:48 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #371** <a href="https://app.graphite.dev/github/pr/penxle/penxle/371?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/371?utm_source=stack-comment).

2023-11-18 07:13 UTC, devunt requested changes

2023-11-18 07:13 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  follows   TagFollow[]
P2: `followers` ?

2023-11-18 07:13 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/tag.ts
> +      });
P2: 요거 제일 밑에서 바로 리턴하게 내려도 되는거 아닌가용

2023-11-18 07:13 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/tag.ts
> +      });
P2: 위와 마찬가지

2023-11-30 18:42 UTC, devunt approved these changes

2023-11-30 18:45 UTC, merged