스페이스 컬렉션 gql
penxle/penxle pull request #378
Opened 2023-11-14 10:50 UTC by robin-maki

2023-11-14 10:50 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #378** <a href="https://app.graphite.dev/github/pr/penxle/penxle/378?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/378?utm_source=stack-comment).

2023-11-18 07:09 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +model Collection {
P2: `PostCollection`...?

2023-11-18 07:09 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  thumbnail   Image?          @relation(fields: [thumbnailId], references: [id])
P2: 제일 앞으로 오게

2023-11-18 07:09 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +
P1: `createdAt` 추가해주세용

2023-11-18 07:09 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +model CollectionPost {
P3: `PostCollectionPost`...? 이상한데... `PostCollectionEntry` ?

2023-11-18 07:09 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  @@unique([collectionId, postId])
P3: 저희 포스트 하나가 컬렉션 여러개에 들어갈 수 있나요?

2023-11-18 07:09 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/collection.ts
> +  createSpaceCollection: t.withAuth({ user: true }).prismaField({
P3: `createPostCollection`...? 고민

2023-11-20 03:11 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +model Collection {
컬렉션은 스페이스에 소속되어 있으니까 `SpaceCollection`은 어떤가요??

2023-11-20 03:13 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +  @@unique([collectionId, postId])
저는 일단 그렇다고 생각은 해요... 최대한 다양하게 컬렉션을 활용할 수 있게 열어줘야 한다고 생각해요

2023-12-07 11:58 UTC, devunt requested changes

2023-12-07 11:58 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/collection.ts
> +      type: ['SpaceCollectionPost'],
P2: 요거 그냥 `Post` 의 배열을 내려주는게 낫지 않을까요?! 프론트에서 order 값을 필요로 할 일은 없을 것 같은 느낌...?!

2023-12-07 11:58 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/collection.ts
> +  updateCollection: t.withAuth({ user: true }).prismaField({
P1: `updateSpaceCollection`

2023-12-08 00:38 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/collection.ts
> +  reorderCollection: t.withAuth({ user: true }).prismaField({
으음... 우리 컬렉션 내 포스트 업데이트 하는게 dnd로 이루어질건데 전체 포스트의 순서를 매번 입력받는건 비효율적이지 않을까요...? 컬렉션의 크기가 커지면 더 그럴 거 같구...

2023-12-08 05:25 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/collection.ts
> +      type: ['SpaceCollectionPost'],
reorder 때 order 값이 필요할 거 같아요!

2023-12-08 05:27 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/collection.ts
> +      type: ['SpaceCollectionPost'],
reorder 시점에는 새 order만 알고 있으면 되는거 아닌가요? 해당 order는 프론트에서 0부터 세서 할 수 있는거 아닌지?!

2023-12-09 06:27 UTC, devunt requested changes

2023-12-09 06:27 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/collection.ts
> +  reorderCollection: t.withAuth({ user: true }).prismaField({
P2: `reorderSpaceCollection`

2023-12-09 06:27 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  state       SpaceCollectionState
P3: 컬렉션도 꼭 soft delete 해야 할까요? 스키마에서 state 빼고 그냥 hard delete 해도 되지 않을지?!

2023-12-09 08:09 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +  state       SpaceCollectionState
컬렉션은 큰 관점에서 컨텐츠라고 볼 수 있다고 생각해서 포스트처럼 soft delete가 유지되도록 짰어요

2023-12-09 08:14 UTC, devunt approved these changes

2023-12-10 01:22 UTC, merged