북마크 db 스키마
penxle/penxle pull request #383
Opened 2023-11-14 13:57 UTC by robin-maki

2023-11-14 13:58 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #383** <a href="https://app.graphite.dev/github/pr/penxle/penxle/383?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/383?utm_source=stack-comment).

2023-11-18 07:00 UTC, devunt requested changes
P3: 저희 포스트 북마크하려면 무조건 북마크 그룹? 있어야 하나요?

2023-11-18 07:00 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  user      User     @relation(fields: [userId], references: [id])
P2: `user`/`userId` 가 제일 앞에 오게 해주세요

2023-11-18 07:00 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +model BookmarkPost {
P2: `PostBookmark` ?

2023-11-18 07:04 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +model Bookmark {
P4: `BookmarkGroup`...?

2023-11-22 04:03 UTC, robin-maki commented
일단 출시때는 그룹이 빠지지만 백엔드상에서 내부적으로 기본 그룹을 하나 만드는 편이 추후 그룹 추가때 더 용이할 거 같아서 디비는 이대로 가져가려고 해요...!

2023-12-04 05:31 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  bookmark   BookmarkGroup @relation(fields: [bookmarkId], references: [id])
P1: `bookmarkGroupId` / `bookmarkGroup`

2023-12-04 06:48 UTC, merged