에디터 디자인 수정사항 반영
penxle/penxle pull request #401
Opened 2023-11-16 12:36 UTC by Seohyun-Roh

2023-11-16 12:37 UTC, Seohyun-Roh commented
Current dependencies on/for this PR:
* main
  * **PR #401** <a href="https://app.graphite.dev/github/pr/penxle/penxle/401?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/401?utm_source=stack-comment).

2023-11-17 03:13 UTC, x86chi requested changes

2023-11-17 03:13 UTC, x86chi commented on apps/penxle.com/src/routes/publish/Header.svelte
> +        </div>
P3: 체크박스처럼 레이블 영역을 클릭하면 스위치가 토글되게 부탁드립니다!

```suggestion
        <label class="flex items-center justify-between">
          <div>
            <p class="body-16-b">게시물 태그 수정 및 등록</p>
            <p class="body-15-m text-secondary">다른 독자들이 게시물의 태그를 수정할 수 있어요</p>
          </div>
          <Switch bind:checked={receiveTagContribution} />
        </label>
```

Switch 컴포넌트를 슬롯으로 레이블을 넣을 수 있는 구조로 개선하면 아래처럼 더 축약해서 가능할 듯:


```svelte
<Switch bind:checked={receiveTagContribution}>
  <p class="body-16-b">게시물 태그 수정 및 등록</p>
  <p class="body-15-m text-secondary">다른 독자들이 게시물의 태그를 수정할 수 있어요</p>
</Switch>
```

2023-11-17 03:13 UTC, x86chi commented on apps/penxle.com/src/routes/publish/Header.svelte
> +              password,
P5: 상태로 form 데이터를 관리하는 구조를 보고 궁금한 내용인데, 만약 폼 데이터를 굳이 상태로 관리할 필요가 없는 경우에도 이렇게 다루는 게 컨벤션인가요..?

2023-11-17 03:34 UTC, x86chi commented on apps/penxle.com/src/routes/publish/Header.svelte
> +              password,
아 `$lib/form` createMutationForm 이 있네요. 이걸로 추후 리펙토링하면 좋아보여요.

2023-11-17 05:46 UTC, x86chi approved these changes

2023-11-17 07:53 UTC, merged