에디터 리팩토링
penxle/penxle pull request #440
Opened 2023-11-18 15:53 UTC by devunt

2023-11-18 15:53 UTC, devunt commented
Current dependencies on/for this PR:
* main
  * **PR #440** <a href="https://app.graphite.dev/github/pr/penxle/penxle/440?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/440?utm_source=stack-comment).

2023-11-19 14:13 UTC, Seohyun-Roh requested changes

2023-11-19 14:13 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/editor/Header.svelte
>          class="text-blue-50 body-15-b rounded-l-none peer-enabled:peer-hover:border-l-border-primary"
P1: 버튼이 툴팁 안에 들어가면서 임시저장 버튼 스타일이 적용이 안되는 것 같아요! 이렇게 수정해주시면 될 것 같습니다.

```suggestion
      <Tooltip class="peer" enabled={!canRevise} message={reviseNotAvailableReason}>
        <Button
          class="body-15-b disabled:border! border-r-none rounded-r-none"
          color="tertiary"
          disabled={!canRevise}
          loading={$revisePost.inflight}
          size="lg"
          variant="outlined"
          on:click={() => doRevisePost('MANUAL_SAVE')}
        >
          임시저장
        </Button>
      </Tooltip>

      <Button
        class="text-blue-50 body-15-b rounded-l-none peer-[&:has(button:enabled)]:peer-hover:border-l-border-primary"
```

2023-11-19 14:13 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/editor/Header.svelte
> +        <MenuItem href={`/${selectedSpace.slug}/preview/${permalink}`} type="link">미리보기</MenuItem>
P2: 미리보기는 새창에서 띄우는 게 좋지 않을까요? 미리보기 페이지로 이동했다가 돌아오면 기존에 작성했던 내용이 사라지고 있습니다.

2023-11-19 14:23 UTC, Seohyun-Roh approved these changes

2023-11-19 14:29 UTC, merged