🗃️ (penxle): prisma 태그 스키마 추가
penxle/penxle pull request #47
Opened 2023-08-09 10:32 UTC by Seohyun-Roh

2023-08-09 11:21 UTC, devunt requested changes

2023-08-09 11:21 UTC, devunt commented on sites/penxle.com/prisma/schema.prisma
> +}
P2: `Wiki` 대신 `TagWiki` 가 좀 더 나을 거 같아요!
P2: 수정한 사람 유저 아이디도 들어가야 하지 않을까요?!

2023-08-09 11:21 UTC, devunt commented on sites/penxle.com/prisma/schema.prisma
> +  relatedTag Tag[]  @relation("related")
P1: 저희 implicit relation 안 씁니다...! explicit relation table로 분리 부탁드려요! (`SpaceMember` 테이블 참고)

2023-08-09 11:21 UTC, devunt commented on sites/penxle.com/prisma/schema.prisma
> +  wiki Wiki[]
P3: 위키 구조를 어떻게 하는게 좋을지 고민해봅시다! 노션에 설계 문서를 적어봐도 좋을 것 같아요.

2023-08-17 08:41 UTC, devunt requested changes

2023-08-17 08:41 UTC, devunt commented on sites/penxle.com/prisma/schema.prisma
> +  tagWikiRevision TagWikiRevision?
P1: `tagWikiRevision` 의 타입은 `TagWikiRevision[]` 이어야 하지 않을까요?! 유저 한명이 태그 위키를 딱 1개만 작성할 수 있는게 아니라 얼마든지 작성할 수 있으니까요!

P4: 요것도 관계가 명확하게 무엇인지 나타내기 위해서는 이름이 `tagWikiRevision` 보다는 `authoredTagWikiRevisions` 정도가 좋은 것 같아요.

2023-08-17 10:13 UTC, Seohyun-Roh commented on sites/penxle.com/prisma/schema.prisma
> +  tagWiki   TagWiki  @relation(fields: [tagWikiId], references: [id])
TagWiki에 TagWikiRevision이 쌓이는 거라고 생각해서 tagWikiId를 참조하도록 했었고, TagWikiRevision에 해당 태그에 대한 정보도 있어야하지 않을까해서 tagId도 같이 참조하도록 했었던 것 같아요.
그런데 TagWiki에 이미 태그에 대한 정보가 있으니 Tag에 대한 참조는 없어도 괜찮을까요..?

2023-08-17 10:25 UTC, Seohyun-Roh commented on sites/penxle.com/prisma/schema.prisma
> +  tagWikiRevision TagWikiRevision?
> P4: 요것도 관계가 명확하게 무엇인지 나타내기 위해서는 이름이 `tagWikiRevision` 보다는 `authoredTagWikiRevisions` 정도가 좋은 것 같아요.

관계가 명확하지 않다는 게 그냥 `tagWikiRevision`은 '해당 유저가 쓴' 느낌이 없다는 뜻일까요..?

2023-09-08 10:52 UTC, devunt approved these changes

2023-09-08 10:58 UTC, merged