포스트 검색엔진 인덱싱
penxle/penxle pull request #483
Opened 2023-11-23 09:56 UTC by robin-maki

2023-11-23 09:56 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #483** <a href="https://app.graphite.dev/github/pr/penxle/penxle/483?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/483?utm_source=stack-comment).

2023-12-09 06:31 UTC, devunt requested changes

2023-12-09 06:31 UTC, devunt commented on apps/penxle.com/scripts/create-search-index.js
> +        searchable: { type: 'boolean' },
P3: 따로 `searchable`이 필요한 이유가 있나요? 검색 불가능한 글은 그냥 인덱스에서 지우면 안 되는건지?!

2023-12-09 06:31 UTC, devunt commented on cspell.config.json
> +    "meilisearch",
P1: 이제 필요 없을 거 같아용

2023-12-09 06:31 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/search.ts
> +      console.log(hits);
P1: 디버깅 라인 제거하기

2023-12-09 07:48 UTC, robin-maki commented on apps/penxle.com/scripts/create-search-index.js
> +        searchable: { type: 'boolean' },
visibility를 변경했다고 인덱스에서 지우거나 재생성하는건 좀 별로인 거 같다고 개인적으론 그렇게 생각했었어요...!

2023-12-09 07:55 UTC, devunt commented on apps/penxle.com/scripts/create-search-index.js
> +        searchable: { type: 'boolean' },
그치만 어떤 경우에도 검색 될 일 없는 포스트가 검색엔진에 인덱싱 되는 것도 이상한... 것... 같아요... ?!

2023-12-10 01:11 UTC, devunt approved these changes

2023-12-10 01:14 UTC, merged