저장 이력 보기 기능 구현
penxle/penxle pull request #484
Opened 2023-11-23 11:19 UTC by x86chi

2023-11-23 11:20 UTC, x86chi commented
Current dependencies on/for this PR:
* main
  * **PR #482** <a href="https://app.graphite.dev/github/pr/penxle/penxle/482?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #305** <a href="https://app.graphite.dev/github/pr/penxle/penxle/305?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #484** <a href="https://app.graphite.dev/github/pr/penxle/penxle/484?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
      * **PR #463** <a href="https://app.graphite.dev/github/pr/penxle/penxle/463?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/484?utm_source=stack-comment).

2023-11-27 09:32 UTC, Seohyun-Roh requested changes

2023-11-27 09:32 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/editor/Header.svelte
```
<script lang="ts>
const revisePost = graphql(`
  mutation EditorPage_RevisePost_Mutation($input: RevisePostInput!) {
    revisePost(input: $input) {
      // ...

      ...EditorPage_RevisionListModal
    }
  }
`);

let revisionList: EditorPage_RevisionListModal;

const doRevisePost = async (revisionKind: PostRevisionKind) => {
  const resp = await revisePost({
    // ...
  });

  revisionList = resp;
};
</script>
```

```
{#if revisionList}
  <MenuItem
    on:click={() => {
      revisionListOpen = true;
    }}
  >
    저장이력
  </MenuItem>
{/if}

{#if revisionList}
  <RevisionListModal $post={revisionList} bind:open={revisionListOpen} />
{/if}
```

P2: 현재 새 글 발행시에는 편집이력을 확인할 수 없는데, 이런식으로 revisePost할 때 리비전 리스트를 받아오면 확인할 수 있을 것 같아요..!

2023-11-27 09:32 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/editor/RevisionListModal.svelte
> +      fragment EditorPage_RevisionListModal on Post {
P3: fragment 이름에 타입도 포함해주세요!

2023-11-27 09:32 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/editor/RevisionListModal.svelte
> +<Modal size="lg" bind:open>
P4: 저장된 이력이 별로 없을 경우에 아래와 같이 보이는데 height를 설정해주는게 좋을 것 같습니다.

<img width="830" alt="image" src="https://github.com/penxle/penxle/assets/76952602/1f7adca6-7e79-4ce9-ade0-876b60e5a93b">

2023-12-04 12:01 UTC, devunt requested changes

2023-12-09 06:59 UTC, devunt requested changes

2023-12-09 06:59 UTC, devunt commented on apps/penxle.com/src/routes/editor/+page.svelte
> +  function resetRestored() {
P1: arrow function 써주세요

2023-12-09 07:08 UTC, devunt approved these changes

2023-12-09 07:13 UTC, Seohyun-Roh approved these changes

2023-12-09 07:16 UTC, merged