나의 펜슬 - 내 포스트 관리
penxle/penxle pull request #494
Opened 2023-11-24 15:28 UTC by x86chi

2023-11-24 15:28 UTC, x86chi commented
Current dependencies on/for this PR:
* main
  * **PR #275** <a href="https://app.graphite.dev/github/pr/penxle/penxle/275?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #494** <a href="https://app.graphite.dev/github/pr/penxle/penxle/494?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #491** <a href="https://app.graphite.dev/github/pr/penxle/penxle/491?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #490** <a href="https://app.graphite.dev/github/pr/penxle/penxle/490?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #486** <a href="https://app.graphite.dev/github/pr/penxle/penxle/486?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/494?utm_source=stack-comment).

2023-11-24 15:39 UTC, x86chi commented on apps/penxle.com/src/routes/(default)/me/posts/+page.svelte
> +        }
@devunt glitch fragment API 의 수정 시 확인할 수 있는 환경을 따로 만들었습니다. 선택한 Post 내 필드를 fragment 로 만들어 이 부분을 아래로 치환해서 작동이 되는지 확인을 부탁드리겠습니다 🙏🏻 

```
...PostManageTableComponent_Post_query
```

2023-11-29 06:16 UTC, Seohyun-Roh requested changes
모바일 디자인 적용안된 부분만 적용 부탁드립니다~
+모바일에서 썸네일 이미지 레이아웃이 살짝 깨지고 `...` 처리가 안되고 있는 것 같습니다.

<img width="314" alt="image" src="https://github.com/penxle/penxle/assets/76952602/dc6c6086-83a7-4920-a95d-47790a0bef26">

2023-11-29 09:03 UTC, Seohyun-Roh approved these changes

2023-11-29 09:06 UTC, merged