숨긴 스페이스 목록
penxle/penxle pull request #499
Opened 2023-11-27 08:18 UTC by Seohyun-Roh

2023-11-27 08:18 UTC, Seohyun-Roh commented
Current dependencies on/for this PR:
* main
  * **PR #499** <a href="https://app.graphite.dev/github/pr/penxle/penxle/499?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/499?utm_source=stack-comment).

2023-11-29 06:20 UTC, x86chi requested changes

2023-11-29 06:20 UTC, x86chi commented on apps/penxle.com/src/routes/(default)/me/settings/contentfilters/MutedSpaceModal.svelte
> +    const { value } = event.currentTarget as HTMLInputElement;
P3: type assertion 사용을 가능한 지양합시다! 입력 이벤트 핸들러 타입을 아래와 같이 직접 참조할 수 있어요! 

```suggestion
  const onInput: FormEventHandler<HTMLInputElement> = (event) => {
    const { value } = event.currentTarget;
```

2023-11-29 06:53 UTC, x86chi requested changes

2023-11-29 06:53 UTC, x86chi commented on apps/penxle.com/src/routes/(default)/me/settings/contentfilters/MutedSpaceModal.svelte
> +    {#each mutedSpaces as space (space.id)}
P2: 검색 결과 좌우 공백 제거 및 쿼리 결과를 불변적으로 참조합시다. 

```suggestion
    query = value.trim()
  };
</script>

<Modal size="md" bind:open>
  <svelte:fragment slot="title">숨긴 스페이스</svelte:fragment>

  <form class="relative h-11.5 w-full mb-4" on:submit|preventDefault>
    <input
      class="rounded-2.5 h-11.5 w-full bg-primary py-1.75 pr-3.5 pl-11 w-full border border-bg-primary transition focus-within:border-tertiary!"
      type="text"
      on:input={onInput}
    />
    <div class="absolute inset-y-0 left-3.5 flex center text-secondary h-100%">
      <span class="i-lc-search square-5 transition" />
    </div>
  </form>

  <ul class="space-y-4">
    {#each mutedSpaces.filter(space => space.name.includes(query)) as space (space.id)}
```

2023-11-29 13:54 UTC, x86chi approved these changes

2023-11-29 14:07 UTC, merged