포스트 DB 구조 변경
penxle/penxle pull request #537
Opened 2023-11-29 10:16 UTC by robin-maki

2023-11-29 10:16 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #537** <a href="https://app.graphite.dev/github/pr/penxle/penxle/537?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/537?utm_source=stack-comment).

2023-12-04 13:23 UTC, devunt requested changes

2023-12-04 13:23 UTC, devunt commented on apps/penxle.com/src/lib/utils/buffer.ts
> +};
P3: 요거 그냥 `Buffer.from(buffer).toString('hex')` 로 안 되는건가여?

2023-12-04 13:50 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +        : undefined;
(메모: fnv1a 등의 비암호학적 해시 알고리즘의 충돌 가능성이 생각보다 높아서(~1/10^5) 폐기)

2023-12-04 13:54 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +    writerTags: t.prismaField({
유저 참여 태그랑 명확하게 구분이 되는 이름이 좀 더 낫다고 생각했어요

2023-12-04 14:09 UTC, robin-maki commented on apps/penxle.com/src/lib/utils/buffer.ts
> +};
되는 것 같네요... 머쓱

2023-12-05 09:49 UTC, devunt requested changes

2023-12-05 09:49 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +      authScopes: { $granted: '$post:edit' },
P3: `withAuth` 아니면 `authScopes` 중에 하나만 써 주세요

2023-12-05 09:49 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +    draftRevision: t.withAuth({ user: true }).prismaField({
P3: `withAuth` 아니면 `authScopes` 중에 하나만 써 주세요

2023-12-05 09:49 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +    writerTags: t.prismaField({
근데 저희가 writer 라는 네이밍을 기존 코드 어디에서도 안 쓰고 있어서... 이미 유저 참여형 태그 기능에 tag contribution이라는 이름이 붙어있는데 작성자 태그를 `tags` 로 하고 유저 참여형 태그를 `tagContribution` 정도로 받는게 낫지 않을지?

2023-12-05 09:49 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
>        unauthorizedResolver: () => 0,
P3: `authScopes`는 빠졌는데 `unauthorizedResolver` 는 남아있는 이유가 있나용

2023-12-05 09:49 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
>        unauthorizedResolver: () => '',
P3: `authScopes`가 없는데 `unauthorizedResolver` 는 있는 이유가 있나용

2023-12-05 09:49 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +        if (!member || (post.state === 'DRAFT' && member.role !== 'ADMIN')) {
P2: `member.role`이 `ADMIN`이 아니라 `MEMBER`일 경우에는 본인이 작성한 포스트의 임시저장본을 못 보는 것 같아요

2023-12-05 09:49 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +          },
P3: 요거 auto save로 기존 리비전 업데이트시에 기존 리비전에 붙이있던 태그 삭제도 되는게 맞나요?

2023-12-05 13:44 UTC, devunt requested changes

2023-12-05 13:44 UTC, devunt commented on apps/penxle.com/src/routes/editor/Header.svelte
> +      mutation EditorPage_UpdatePostOptions_Mutation($input: PublishPostInput!) {
P1: 이름 `EditorPage_PublishPost_Mutation` 으로 바꿔주세요

2023-12-05 13:44 UTC, devunt commented on apps/penxle.com/src/routes/(default)/[space]/Post.svelte
> +          ...Image_image
P1: `id` 도 필드에 넣어주세요

2023-12-05 13:44 UTC, devunt commented on apps/penxle.com/src/routes/(default)/[space]/Post.svelte
> +  $: croppedThumbnail = $postRevision.croppedThumbnail as FragmentType<Image_image>;
```suggestion
  let croppedThumbnail: FragmentType<Image_image>;
  $: croppedThumbnail = $postRevision.croppedThumbnail;
```

P2: reactive variable의 경우 요렇게 타입 선언을 하는 것을 추천드립니다

2023-12-05 13:44 UTC, devunt commented on apps/penxle.com/src/lib/components/Feed.svelte
> +            ...Image_image
P1: `id` 도 포함시켜서 가져와주세요

2023-12-05 14:56 UTC, robin-maki commented on apps/penxle.com/src/routes/(default)/[space]/Post.svelte
> +  $: croppedThumbnail = $postRevision.croppedThumbnail as FragmentType<Image_image>;
`as FragmentType<Image_image>`을 빼면 `$postRevision.croppedThumbnail`이 `undefined`일 수 있다는 타입 오류가 나네요... 

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/OIyHyV8T3If5OJv5ys3X/643ebff9-db50-4d0f-bd33-02376e4cbf91.png)

2023-12-05 14:57 UTC, devunt commented on apps/penxle.com/src/routes/(default)/[space]/Post.svelte
> +  $: croppedThumbnail = $postRevision.croppedThumbnail as FragmentType<Image_image>;
`let croppedThumbnail: FragmentType<Image_image> | undefined` 로 하면 되지 않을가용 (실제로도 undefined일 수 있는거 아니에요?)

2023-12-05 14:59 UTC, robin-maki commented on apps/penxle.com/src/routes/(default)/[space]/Post.svelte
> +  $: croppedThumbnail = $postRevision.croppedThumbnail as FragmentType<Image_image>;
사실 `croppedThumbnail`은 존재하지 않을 가능성이 있으니까 변수 선언을 ` | undefined | null`로 해봤는데 이젠 다른 오류가 나요...
```
Type '({ id: string; } & { ' $fragmentRefs'?: { Image_image: Image_image; } | undefined; }) | null | undefined' is not assignable to type 'FragmentType<Image_image> | null | undefined'.
  Type '{ id: string; } & { ' $fragmentRefs'?: { Image_image: Image_image; } | undefined; }' is not assignable to type 'FragmentType<Image_image> | null | undefined'.
    Type '{ id: string; } & { ' $fragmentRefs'?: { Image_image: Image_image; } | undefined; }' is missing the following properties from type 'FragmentType<Image_image>': url, width, height, placeholderts(2322)

let croppedThumbnail: FragmentType<Image_image> | null | undefined
```

2023-12-05 14:59 UTC, devunt commented on apps/penxle.com/src/routes/(default)/[space]/Post.svelte
> +  $: croppedThumbnail = $postRevision.croppedThumbnail as FragmentType<Image_image>;
근데 일단 애초에 `croppedThumbnail`을 왜 `FragmentType<Image_image>` 로 캐스팅하는지도 잘 모르겠는데... `<Image>` 컴포넌트에 넘기는거도 아닌 거 같은데 그냥 `id`랑 `url` 가져오면 되는거 아닌가요

2023-12-05 15:02 UTC, robin-maki commented on apps/penxle.com/src/routes/(default)/[space]/Post.svelte
> +  $: croppedThumbnail = $postRevision.croppedThumbnail as FragmentType<Image_image>;
캐스팅 없이 바로 프로퍼티 참조하려니까 
```
Property 'url' does not exist on type '{ id: string; } & { ' $fragmentRefs'?: { Image_image: Image_image; } | undefined; }'.ts(2339)
```
오류가 나서 나스님께 물어본 방식대로 짰었어요...

2023-12-05 15:06 UTC, devunt commented on apps/penxle.com/src/routes/(default)/[space]/Post.svelte
> +  $: croppedThumbnail = $postRevision.croppedThumbnail as FragmentType<Image_image>;
그러니까 지금 `Post.svelte` 컴포넌트가 실제로 필요로 하는건 `croppedThumbnail`의 `url` 인건데 왜 graphql에서 `croppedThumbnail` 안의 `...Image_image` fragment를 가져오려고 하는지? `Image_image` fragment는 `<Image>` 컴포넌트에 해당 이미지를 넘겨주려고 할 때 필요한건데 지금 `<Image $image={croppedThumbnail} />` 같은 코드가 없잖아요

2023-12-05 15:21 UTC, merged