라디오버튼 컴포넌트 추가
penxle/penxle pull request #601
Opened 2023-12-04 09:11 UTC by Seohyun-Roh

2023-12-04 09:45 UTC, x86chi requested changes

2023-12-04 09:45 UTC, x86chi commented on apps/penxle.com/src/lib/components/forms/Radio.svelte
> +/>
P2: Switch 와 Checkbox 처럼 slot 으로 레이블을 지정 가능하게 바꿔주세요!

2023-12-04 11:44 UTC, devunt approved these changes

2023-12-04 11:49 UTC, x86chi commented on apps/penxle.com/src/lib/components/forms/Radio.svelte
> +  export let checked: boolean | undefined = undefined;
```suggestion
  type $$Props = HTMLInputAttributes;

  let _class: $$Props['class'] = undefined;
  export { _class as class };
  export let name: $$Props['name'] = undefined;
```

P3: 컴포넌트 props 타입 정의가 필요해요!

2023-12-05 09:58 UTC, x86chi approved these changes

2023-12-05 10:20 UTC, merged