Post.myBookmarks 필드 추가
penxle/penxle pull request #632
Opened 2023-12-07 08:39 UTC by robin-maki

2023-12-07 08:39 UTC, robin-maki commented
Current dependencies on/for this PR:
* main
  * **PR #632** <a href="https://app.graphite.dev/github/pr/penxle/penxle/632?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/632?utm_source=stack-comment).

2023-12-07 12:03 UTC, devunt requested changes

2023-12-07 12:03 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +              userId: context.session?.userId,
P2: 이거 비로그인 유저가 이 필드 요청하면 이 포스트에 북마크한 `BookmarkGroupPost`  전체를 db에서 매번 긁어오는 것 같아용

2023-12-07 12:03 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +      type: ['BookmarkGroupPost'],
P4: `myBookmarks` 라는 이름인데 실제 타입은 `BookmarkGroupPost` 를 리턴하는게 좀 이상한 느낌...?!

2023-12-08 06:06 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +      type: ['BookmarkGroupPost'],
무언가 자신의 북마크를 보여줄 필드 자체는 필요한데 이걸 어떻게 이름을 지어야 / 뭘 리턴해야 지금보다 더 좋을지 감이 잘 안 잡히네요...

2023-12-09 02:37 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +      type: ['BookmarkGroupPost'],
`bookmarkedGroups` 로 하고 `BookmarkGroup` 을 리턴하는건 어떨까요? 그리고 북마크 삭제할 때는 `bookmarkGroupId` 랑 `postId` 를 받는다거나?

2023-12-09 06:33 UTC, devunt approved these changes

2023-12-09 07:13 UTC, merged