DigitsInput 컴포넌트 구현, 이메일 코드 인증 화면에 적용
penxle/penxle pull request #660
Opened 2023-12-09 11:02 UTC by dolsup

<img width="382" alt="스크린샷 2023-12-09 오후 7 52 54" src="https://github.com/penxle/penxle/assets/8360934/396a8c7d-0fc6-4b93-ae79-7d23b2dc15bc">

TextInput 컴포넌트를 참고해서 만들었습니다.
input이 1개입니다. 접근성 면에서 좋습니다 (autocomplete, 복붙 가능)

2023-12-09 11:46 UTC, devunt submitted a review, later dismissed
👍

2023-12-09 11:53 UTC, devunt requested changes
https://penxle-com-pr-660.pnxl.site/login/code?email=devunt@gmail.com

<img width="528" alt="CleanShot 2023-12-09 at 20 53 04" src="https://github.com/penxle/penxle/assets/337728/89032e38-8137-4bd1-948b-bcdba26c97c7">

뭔가 잘 안 돼욧...!

2023-12-09 13:34 UTC, dolsup commented
`right-[calc(((2.5rem-1ch)/2+0.5rem)*-1)] tracking-[calc(2.5rem-1ch+0.5rem)] indent-[calc((2.5rem-1ch)/2)]`
이 클래스들이 로컬에서는 css로 잘 만들어지는데 배포된 환경에서는 없네요

2023-12-09 13:47 UTC, dolsup commented
https://stackoverflow.com/a/72770208

클래스가 template literal이면 생성이 안 되는군요.. 개발 환경에서는 virtual css 모듈이 동적으로 해주지만..

2023-12-10 00:46 UTC, devunt commented
Current dependencies on/for this PR:
* main
  * **PR #660** <a href="https://app.graphite.dev/github/pr/penxle/penxle/660?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/660?utm_source=stack-comment).

2023-12-10 01:05 UTC, devunt approved these changes

2023-12-10 01:12 UTC, merged