비밀번호 찾기 gql
penxle/penxle pull request #74
Opened 2023-09-06 08:15 UTC by robin-maki

2023-09-06 08:17 UTC, robin-maki commented
일단 메일 발송 부분은 TODO 해 놨어요

2023-09-08 08:33 UTC, devunt requested changes

2023-09-08 08:33 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  createdAt DateTime                      @default(now()) @map("created_at") @db.Timestamptz
P2: expiresAt 을 실시간 계산하는게 아니라 레코드 생성 시점에 넣는게 좋을 것 같아요.

2023-09-08 08:33 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  state     UserPasswordResetRequestState @default(PENDING)
P4: state를 두지 않고 그냥 만료되거나 완료되면 레코드를 지우는건 어떨까요? 비밀번호 초기화 기록은 딱히 놔둘 필요가 없을 것 같기도 하고... 아닌가 놔둬야 할 것 같기도 하고...

2023-09-08 08:33 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  ACCEPTED
P5: `ACCEPTED` 보다는 `FULFILLED` 가 더 적당해보이기도요.

2023-09-08 08:33 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +  .asMilliseconds();
P1: 현재 코드베이스상 dayjs는 request가 들어오는 시점에 초기화돼서, 최상위 scope에서는 호출이 불가능합니다 (본 PR 빌드가 실패하는 이유). 최상위에서도 호출이 가능하게 고쳐야 하긴 하는데 일단 그 전까지는 request context 내에서 호출하게 바꿔주세요.

2023-09-08 08:33 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +    }),
P2: 위에서 말한 것처럼 실시간 계산이 아닌 생성 시점에 계산하는건 어떨까요?

2023-09-08 08:33 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +        throw new NotFoundError();
P1: 이 경우에는 `NotFoundError` 가 아닌 `FormValidationError`를 리턴합니다. 타겟 필드는 `email` 이 되겠군요.

2023-09-08 08:33 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/user.ts
> +        throw new NotFoundError();
P2: token이 잘못 들어오는건 가능할만한 시나리오가 아니기에 (주로 expected error를 뜻하는) `NotFoundError` 를 리턴할 필요는 없을 것 같아요. 그냥 위에서 findUnique 대신 findUniqueOrThrow를 쓰고 체크 조건을 다 쿼리 안쪽으로 옮기는게 어떨지?

2023-09-08 08:33 UTC, devunt commented on apps/penxle.com/src/lib/validations/user.ts
> +  password: z.string().min(8, '8자 이상으로 입력해주세요'),
P3: 이메일과 비밀번호 조건이 앞으로 이곳 저곳 쓰일 것 같으니 `EmailSchema`와 `PasswordSchema` 를 별도로 빼는 것도 좋아보입니다.

2023-09-08 09:33 UTC, robin-maki commented on apps/penxle.com/src/lib/validations/user.ts
> +  password: z.string().min(8, '8자 이상으로 입력해주세요'),
회원가입시 스키마(길이 제한 등 좀 더 자세히 체크)랑 로그인시 스키마(최소 조건만 검사) 같이 차이가 있는 부분이 있는데 이걸 조건이 더 빡센 회원가입시로 통일시켜도 괜찮을까요? (일단 전 괜찮다고 생각해요)

2023-09-08 09:41 UTC, robin-maki commented
> P4: state를 두지 않고 그냥 만료되거나 완료되면 레코드를 지우는건 어떨까요? 비밀번호 초기화 기록은 딱히 놔둘 필요가 없을 것 같기도 하고... 아닌가 놔둬야 할 것 같기도 하고...

에서 말씀주신 대로 state 없이 레코드를 지우는 방향으로 재설계했습니다!

2023-09-08 10:24 UTC, devunt commented on apps/penxle.com/src/lib/validations/user.ts
> +  password: z.string().min(8, '8자 이상으로 입력해주세요'),
일단 지금 회원가입시에도 길이 제한 체크만 들어가 있죠? 저는 이런저런거 강제하는거 별로 안 좋아해서 앞으로도 그럴 거 같긴 해요. 통일해도 괜찮을 것 같습니다.

2023-09-08 10:27 UTC, devunt requested changes

2023-09-08 10:27 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  expiresAt DateTime @default(dbgenerated("now() + interval '1 hour'")) @map("expires_at") @db.Timestamptz
P2: expiresAt 넣을 때 DB 말고 코드에서 넣어주세욧 (db에 로직이 들어있으면 추후에 동작 파악하기가 어렵습니당)

2023-09-08 10:28 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  expiresAt DateTime @default(dbgenerated("now() + interval '1 hour'")) @map("expires_at") @db.Timestamptz
`dayjs().add(1, 'hour').toDate()` 하면 되던가 그럴거에용

2023-09-08 10:29 UTC, devunt commented
나머지는 메일 발송이랑 구글 프로필 사진 적용까지 완료되면 그때 최종 리뷰하고 머지합시다

2023-09-08 12:06 UTC, robin-maki commented
메일 발송 + 비밀번호 변경 테스트 완료했습니다!

2023-09-08 12:13 UTC, devunt approved these changes

2023-09-08 12:13 UTC, merged