알림 gql
penxle/penxle pull request #926
Opened 2023-12-20 07:26 UTC by robin-maki

2023-12-20 07:26 UTC, robin-maki commented
Current dependencies on/for this PR:
* `main`
  * **PR #926** <a href="https://app.graphite.dev/github/pr/penxle/penxle/926?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/926?utm_source=stack-comment).

2024-01-16 05:34 UTC, devunt requested changes

2024-01-16 05:34 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  profile   Profile?                 @relation(fields: [profileId], references: [id])
P2: 받는 유저는 `user` 고 행동한 사람이 `profile`인 것 같은데 네이밍이 좀 혼란스러운 거 같아용
P3: 애초에 `profile`을 저장해야 할 이유가 있을지? 이거도 고민해봐도 조을 듯

2024-01-16 05:34 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  data      Json?
P2: 웹사이트에서 알림을 클릭했을 때 어디로 가야 할지? `href` 같은 필드가 있어도 좋을 듯 한?

2024-01-16 06:16 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +  profile   Profile?                 @relation(fields: [profileId], references: [id])
<img width="610" alt="image" src="https://github.com/penxle/penxle/assets/8201350/30444e3c-a01d-46e2-b62d-b8da94c461ab">
트위터 알림처럼 비슷한 알림들을 합쳐서 보여줘야 하지 않나 하는 생각이 들어서 일단 프로필을 저장하기로 했어요

2024-01-16 07:37 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +  data      Json?
지금 href를 넣어서 짜긴 했는데 생각해보니까 이걸 프론트측에서 data 기반으로 생성하는 편이 더 맞을 거 같아요 (지금 스페이스 관심추가시 스페이스로 링크 -> 나중에 독자 관리로 링크 이렇게 변경될 때 이전에 쌓인 알림이라고 링크가 달라지면 좀 이상할 거 같아요...)

2024-01-16 07:41 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  data      Json?
흠 말씀하신 면에서는 그 편이 더 나은 거 같긴 한데... 잘 모르겠네용

2024-01-16 07:45 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +  data      Json?
아니면 알림 확인 전용 엔드포인트를 만들어서 그곳에서 적당히 리다이렉트를 시켜주는 방안도 생각해봤어요... (이메일 알림에서의 링크 핸들링은 이 방법이 더 나을 거 같아요)

2024-01-16 08:28 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  data      Json?
흠 그러게요 그게 제일 낫겠네요! `/api/notification/${notificationId}` 요쪽으로 날려버리면 조을 듯

2024-01-16 08:29 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  data      Json?
구럼 href 는 다시 빼는걸로 !! 🙏

2024-01-17 02:43 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +  data      Json?
알림 엔드포인트를 여기 스택에 합치기에는 너무 비대해질 거 같아서 일단은 스택 분리할게요! 분리할 수 있는 기능이면 분리해야 한다 생각하기도 하고...

2024-01-17 06:43 UTC, devunt requested changes

2024-01-17 06:43 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  profile   Profile?                 @relation(fields: [profileId], references: [id])
P2: 이거 이름이 `profile`이 맞는지는 아직 유효한 문제제기인 것 같아요. `user`랑 `profile` 은 보통 같은 유저의 것으로 묶어다니는 경우가 많은데 (`SpaceMember`나 `Post` 등) 여기서는 `user`와 `profile`이 서로 다른 유저인 것 같아서...?

2024-01-17 07:32 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +  profile   Profile?                 @relation(fields: [profileId], references: [id])
`targetProfile`...?

2024-01-17 08:37 UTC, robin-maki commented on apps/penxle.com/prisma/schema.prisma
> +  profile   Profile?                 @relation(fields: [profileId], references: [id])
`actor`로 변경했습니다!

2024-01-17 08:40 UTC, devunt requested changes

2024-01-17 08:40 UTC, devunt commented on apps/penxle.com/prisma/schema.prisma
> +  href      String?
P2: `href` 빠지기로 한거 아니였나욤

2024-01-17 08:43 UTC, devunt approved these changes
👍

2024-01-17 08:53 UTC, merged