독자 프로필 시스템 구축
penxle/penxle pull request #935
Opened 2023-12-20 10:40 UTC by robin-maki

2023-12-20 10:41 UTC, robin-maki commented
Current dependencies on/for this PR:
* `main`
  * **PR #935** <a href="https://app.graphite.dev/github/pr/penxle/penxle/935?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/935?utm_source=stack-comment).

2024-01-16 05:40 UTC, devunt requested changes

2024-01-16 05:40 UTC, devunt commented on apps/penxle.com/src/lib/utils/name.ts
> +];
P2: 요거 어디서 가져온걸까요? 지금은 스페이스당 612개까지 중복 없이 나오는데 훨씬 더 조합 가짓수가 많아야 할 것 같기도 한 느낌...

2024-01-16 05:40 UTC, devunt commented on apps/penxle.com/src/lib/utils/name.ts
> +import fnv1a from '@sindresorhus/fnv1a';
P2: 요거 그냥 `@sindresorhus/string-hash` 쓰면 안 되나용 (이미 디펜던시 걸려있음)

2024-01-16 05:54 UTC, robin-maki commented on apps/penxle.com/src/lib/utils/name.ts
> +];
이거 제가 그냥 즉석에서 지어낸건데요 확실히 더 많은 가짓수가 필요할 거 같아요

2024-01-16 05:59 UTC, devunt commented on apps/penxle.com/src/lib/utils/name.ts
> +];
뭔가 좀 더 좋은 소스가 있으면 좋을 거 같은데 한번 찾아보도록 하죠

2024-01-16 08:30 UTC, devunt approved these changes

2024-01-17 08:02 UTC, merged