스페이스 컬렉션 상세 페이지 모바일 레이아웃 업데이트
penxle/penxle pull request #970
Opened 2023-12-22 11:50 UTC by x86chi

디자인 목업에서 시간 상 적용하지 못한 부분을 마저 붙였습니다.

2023-12-22 11:50 UTC, x86chi commented
Current dependencies on/for this PR:
* `main`
  * **PR #970** <a href="https://app.graphite.dev/github/pr/penxle/penxle/970?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/970?utm_source=stack-comment).

2023-12-26 03:01 UTC, Seohyun-Roh requested changes

2023-12-26 03:01 UTC, Seohyun-Roh commented on apps/penxle.com/src/routes/(default)/[space]/(space)/collections/[entity]/+page@(default).svelte
> +<svelte:window
P3: window 전체에 걸리는 이벤트이니 마크업 맨 위에 놓는게 어떨까요?

2023-12-27 11:24 UTC, Seohyun-Roh approved these changes

2023-12-27 11:32 UTC, merged