reindexSearch gql 스키마 잘못되어 있었던 것 수정
penxle/penxle pull request #985
Opened 2023-12-26 10:15 UTC by robin-maki

2023-12-26 10:15 UTC, robin-maki commented
Current dependencies on/for this PR:
* `main`
  * **PR #985** <a href="https://app.graphite.dev/github/pr/penxle/penxle/985?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/985?utm_source=stack-comment).

2023-12-27 11:32 UTC, devunt requested changes

2023-12-27 11:32 UTC, devunt commented on apps/penxle.com/schema.graphql
> +
P1: 빼주세용

2023-12-30 11:46 UTC, devunt approved these changes

2023-12-30 11:59 UTC, merged